#the energy deposition in the phantom
/score/create/boxMesh boxMesh_1
/score/mesh/boxSize 200.0 5.0 20.0 mm
/score/mesh/nBin 1 1 1
/score/mesh/translate/xyz 0.0 -150.0 0.0  mm
# scoring spectra
/score/quantity/flatSurfaceFlux fux0 
/score/filter/particleWithKineticEnergy range0 0.0 10.0 keV gamma
/score/quantity/flatSurfaceFlux fux1 
/score/filter/particleWithKineticEnergy range1 10.0 20.0 keV gamma
/score/quantity/flatSurfaceFlux fux2 
/score/filter/particleWithKineticEnergy range2 20.0 30.0 keV gamma
/score/quantity/flatSurfaceFlux fux3 
/score/filter/particleWithKineticEnergy range3 30.0 40.0 keV gamma
/score/quantity/flatSurfaceFlux fux4 
/score/filter/particleWithKineticEnergy range4 40.0 50.0 keV gamma
/score/quantity/flatSurfaceFlux fux5 
/score/filter/particleWithKineticEnergy range5 50.0 60.0 keV gamma
/score/quantity/flatSurfaceFlux fux6 
/score/filter/particleWithKineticEnergy range6 60.0 70.0 keV gamma
/score/quantity/flatSurfaceFlux fux7 
/score/filter/particleWithKineticEnergy range7 70.0 80.0 keV gamma
/score/quantity/flatSurfaceFlux fux8 
/score/filter/particleWithKineticEnergy range8 80.0 90.0 keV gamma
/score/quantity/flatSurfaceFlux fux9 
/score/filter/particleWithKineticEnergy range9 90.0 100.0 keV gamma
/score/quantity/flatSurfaceFlux fux10 
/score/filter/particleWithKineticEnergy range10 100.0 110.0 keV gamma
/score/quantity/flatSurfaceFlux fux11 
/score/filter/particleWithKineticEnergy range11 110.0 120.0 keV gamma
/score/quantity/flatSurfaceFlux fux12 
/score/filter/particleWithKineticEnergy range12 120.0 130.0 keV gamma
/score/quantity/flatSurfaceFlux fux13 
/score/filter/particleWithKineticEnergy range13 130.0 140.0 keV gamma
/score/quantity/flatSurfaceFlux fux14 
/score/filter/particleWithKineticEnergy range14 140.0 150.0 keV gamma
/score/quantity/flatSurfaceFlux fux15 
/score/filter/particleWithKineticEnergy range15 150.0 160.0 keV gamma
/score/quantity/flatSurfaceFlux fux16 
/score/filter/particleWithKineticEnergy range16 160.0 170.0 keV gamma
/score/quantity/flatSurfaceFlux fux17 
/score/filter/particleWithKineticEnergy range17 170.0 180.0 keV gamma
/score/quantity/flatSurfaceFlux fux18 
/score/filter/particleWithKineticEnergy range18 180.0 190.0 keV gamma
/score/quantity/flatSurfaceFlux fux19 
/score/filter/particleWithKineticEnergy range19 190.0 200.0 keV gamma
/score/quantity/flatSurfaceFlux fux20 
/score/filter/particleWithKineticEnergy range20 200.0 210.0 keV gamma
/score/quantity/flatSurfaceFlux fux21 
/score/filter/particleWithKineticEnergy range21 210.0 220.0 keV gamma
/score/quantity/flatSurfaceFlux fux22 
/score/filter/particleWithKineticEnergy range22 220.0 230.0 keV gamma
/score/quantity/flatSurfaceFlux fux23 
/score/filter/particleWithKineticEnergy range23 230.0 240.0 keV gamma
/score/quantity/flatSurfaceFlux fux24 
/score/filter/particleWithKineticEnergy range24 240.0 250.0 keV gamma
/score/quantity/flatSurfaceFlux fux25 
/score/filter/particleWithKineticEnergy range25 250.0 260.0 keV gamma
/score/quantity/flatSurfaceFlux fux26 
/score/filter/particleWithKineticEnergy range26 260.0 270.0 keV gamma
/score/quantity/flatSurfaceFlux fux27 
/score/filter/particleWithKineticEnergy range27 270.0 280.0 keV gamma
/score/quantity/flatSurfaceFlux fux28 
/score/filter/particleWithKineticEnergy range28 280.0 290.0 keV gamma
/score/quantity/flatSurfaceFlux fux29 
/score/filter/particleWithKineticEnergy range29 290.0 300.0 keV gamma
/score/quantity/flatSurfaceFlux fux30 
/score/filter/particleWithKineticEnergy range30 300.0 310.0 keV gamma
/score/quantity/flatSurfaceFlux fux31 
/score/filter/particleWithKineticEnergy range31 310.0 320.0 keV gamma
/score/quantity/flatSurfaceFlux fux32 
/score/filter/particleWithKineticEnergy range32 320.0 330.0 keV gamma
/score/quantity/flatSurfaceFlux fux33 
/score/filter/particleWithKineticEnergy range33 330.0 340.0 keV gamma
/score/quantity/flatSurfaceFlux fux34 
/score/filter/particleWithKineticEnergy range34 340.0 350.0 keV gamma
/score/quantity/flatSurfaceFlux fux35 
/score/filter/particleWithKineticEnergy range35 350.0 360.0 keV gamma
/score/quantity/flatSurfaceFlux fux36 
/score/filter/particleWithKineticEnergy range36 360.0 370.0 keV gamma
/score/quantity/flatSurfaceFlux fux37 
/score/filter/particleWithKineticEnergy range37 370.0 380.0 keV gamma
/score/quantity/flatSurfaceFlux fux38 
/score/filter/particleWithKineticEnergy range38 380.0 390.0 keV gamma
/score/quantity/flatSurfaceFlux fux39 
/score/filter/particleWithKineticEnergy range39 390.0 400.0 keV gamma
/score/quantity/flatSurfaceFlux fux40 
/score/filter/particleWithKineticEnergy range40 400.0 410.0 keV gamma
/score/quantity/flatSurfaceFlux fux41 
/score/filter/particleWithKineticEnergy range41 410.0 420.0 keV gamma
/score/quantity/flatSurfaceFlux fux42 
/score/filter/particleWithKineticEnergy range42 420.0 430.0 keV gamma
/score/quantity/flatSurfaceFlux fux43 
/score/filter/particleWithKineticEnergy range43 430.0 440.0 keV gamma
/score/quantity/flatSurfaceFlux fux44 
/score/filter/particleWithKineticEnergy range44 440.0 450.0 keV gamma
/score/quantity/flatSurfaceFlux fux45 
/score/filter/particleWithKineticEnergy range45 450.0 460.0 keV gamma
/score/quantity/flatSurfaceFlux fux46 
/score/filter/particleWithKineticEnergy range46 460.0 470.0 keV gamma
/score/quantity/flatSurfaceFlux fux47 
/score/filter/particleWithKineticEnergy range47 470.0 480.0 keV gamma
/score/quantity/flatSurfaceFlux fux48 
/score/filter/particleWithKineticEnergy range48 480.0 490.0 keV gamma
/score/quantity/flatSurfaceFlux fux49 
/score/filter/particleWithKineticEnergy range49 490.0 501.0 keV gamma
/score/quantity/flatSurfaceFlux fux50 
/score/filter/particleWithKineticEnergy range50 501.0 511.0 keV gamma
/score/quantity/flatSurfaceFlux fux51 
/score/filter/particleWithKineticEnergy range51 511.0 521.0 keV gamma
/score/quantity/flatSurfaceFlux fux52 
/score/filter/particleWithKineticEnergy range52 521.0 531.0 keV gamma
/score/quantity/flatSurfaceFlux fux53 
/score/filter/particleWithKineticEnergy range53 531.0 541.0 keV gamma
/score/quantity/flatSurfaceFlux fux54 
/score/filter/particleWithKineticEnergy range54 541.0 551.0 keV gamma
/score/quantity/flatSurfaceFlux fux55 
/score/filter/particleWithKineticEnergy range55 551.0 561.0 keV gamma
/score/quantity/flatSurfaceFlux fux56 
/score/filter/particleWithKineticEnergy range56 561.0 571.0 keV gamma
/score/quantity/flatSurfaceFlux fux57 
/score/filter/particleWithKineticEnergy range57 571.0 581.0 keV gamma
/score/quantity/flatSurfaceFlux fux58 
/score/filter/particleWithKineticEnergy range58 581.0 591.0 keV gamma
/score/quantity/flatSurfaceFlux fux59 
/score/filter/particleWithKineticEnergy range59 591.0 601.0 keV gamma
/score/quantity/flatSurfaceFlux fux60 
/score/filter/particleWithKineticEnergy range60 601.0 611.0 keV gamma
/score/quantity/flatSurfaceFlux fux61 
/score/filter/particleWithKineticEnergy range61 611.0 621.0 keV gamma
/score/quantity/flatSurfaceFlux fux62 
/score/filter/particleWithKineticEnergy range62 621.0 631.0 keV gamma
/score/quantity/flatSurfaceFlux fux63 
/score/filter/particleWithKineticEnergy range63 631.0 641.0 keV gamma
/score/quantity/flatSurfaceFlux fux64 
/score/filter/particleWithKineticEnergy range64 641.0 651.0 keV gamma
/score/quantity/flatSurfaceFlux fux65 
/score/filter/particleWithKineticEnergy range65 651.0 661.0 keV gamma
/score/quantity/flatSurfaceFlux fux66 
/score/filter/particleWithKineticEnergy range66 661.0 671.0 keV gamma
/score/quantity/flatSurfaceFlux fux67 
/score/filter/particleWithKineticEnergy range67 671.0 681.0 keV gamma
/score/quantity/flatSurfaceFlux fux68 
/score/filter/particleWithKineticEnergy range68 681.0 691.0 keV gamma
/score/quantity/flatSurfaceFlux fux69 
/score/filter/particleWithKineticEnergy range69 691.0 701.0 keV gamma
/score/quantity/flatSurfaceFlux fux70 
/score/filter/particleWithKineticEnergy range70 701.0 711.0 keV gamma
/score/quantity/flatSurfaceFlux fux71 
/score/filter/particleWithKineticEnergy range71 711.0 721.0 keV gamma
/score/quantity/flatSurfaceFlux fux72 
/score/filter/particleWithKineticEnergy range72 721.0 731.0 keV gamma
/score/quantity/flatSurfaceFlux fux73 
/score/filter/particleWithKineticEnergy range73 731.0 741.0 keV gamma
/score/quantity/flatSurfaceFlux fux74 
/score/filter/particleWithKineticEnergy range74 741.0 751.0 keV gamma
/score/quantity/flatSurfaceFlux fux75 
/score/filter/particleWithKineticEnergy range75 751.0 761.0 keV gamma
/score/quantity/flatSurfaceFlux fux76 
/score/filter/particleWithKineticEnergy range76 761.0 771.0 keV gamma
/score/quantity/flatSurfaceFlux fux77 
/score/filter/particleWithKineticEnergy range77 771.0 781.0 keV gamma
/score/quantity/flatSurfaceFlux fux78 
/score/filter/particleWithKineticEnergy range78 781.0 791.0 keV gamma
/score/quantity/flatSurfaceFlux fux79 
/score/filter/particleWithKineticEnergy range79 791.0 801.0 keV gamma
/score/quantity/flatSurfaceFlux fux80 
/score/filter/particleWithKineticEnergy range80 801.0 811.0 keV gamma
/score/quantity/flatSurfaceFlux fux81 
/score/filter/particleWithKineticEnergy range81 811.0 821.0 keV gamma
/score/quantity/flatSurfaceFlux fux82 
/score/filter/particleWithKineticEnergy range82 821.0 831.0 keV gamma
/score/quantity/flatSurfaceFlux fux83 
/score/filter/particleWithKineticEnergy range83 831.0 841.0 keV gamma
/score/quantity/flatSurfaceFlux fux84 
/score/filter/particleWithKineticEnergy range84 841.0 851.0 keV gamma
/score/quantity/flatSurfaceFlux fux85 
/score/filter/particleWithKineticEnergy range85 851.0 861.0 keV gamma
/score/quantity/flatSurfaceFlux fux86 
/score/filter/particleWithKineticEnergy range86 861.0 871.0 keV gamma
/score/quantity/flatSurfaceFlux fux87 
/score/filter/particleWithKineticEnergy range87 871.0 881.0 keV gamma
/score/quantity/flatSurfaceFlux fux88 
/score/filter/particleWithKineticEnergy range88 881.0 891.0 keV gamma
/score/quantity/flatSurfaceFlux fux89 
/score/filter/particleWithKineticEnergy range89 891.0 901.0 keV gamma
/score/quantity/flatSurfaceFlux fux90 
/score/filter/particleWithKineticEnergy range90 901.0 911.0 keV gamma
/score/quantity/flatSurfaceFlux fux91 
/score/filter/particleWithKineticEnergy range91 911.0 921.0 keV gamma
/score/quantity/flatSurfaceFlux fux92 
/score/filter/particleWithKineticEnergy range92 921.0 931.0 keV gamma
/score/quantity/flatSurfaceFlux fux93 
/score/filter/particleWithKineticEnergy range93 931.0 941.0 keV gamma
/score/quantity/flatSurfaceFlux fux94 
/score/filter/particleWithKineticEnergy range94 941.0 951.0 keV gamma
/score/quantity/flatSurfaceFlux fux95 
/score/filter/particleWithKineticEnergy range95 951.0 961.0 keV gamma
/score/quantity/flatSurfaceFlux fux96 
/score/filter/particleWithKineticEnergy range96 961.0 971.0 keV gamma
/score/quantity/flatSurfaceFlux fux97 
/score/filter/particleWithKineticEnergy range97 971.0 981.0 keV gamma
/score/quantity/flatSurfaceFlux fux98 
/score/filter/particleWithKineticEnergy range98 981.0 991.0 keV gamma
/score/quantity/flatSurfaceFlux fux99 
/score/filter/particleWithKineticEnergy range99 991.0 1001.0 keV gamma
/score/quantity/flatSurfaceFlux fux100 
/score/filter/particleWithKineticEnergy range100 1001.0 1011.0 keV gamma
/score/quantity/flatSurfaceFlux fux101 
/score/filter/particleWithKineticEnergy range101 1011.0 1021.0 keV gamma
/score/quantity/flatSurfaceFlux fux102 
/score/filter/particleWithKineticEnergy range102 1021.0 1031.0 keV gamma
/score/quantity/flatSurfaceFlux fux103 
/score/filter/particleWithKineticEnergy range103 1031.0 1041.0 keV gamma
/score/quantity/flatSurfaceFlux fux104 
/score/filter/particleWithKineticEnergy range104 1041.0 1051.0 keV gamma
/score/quantity/flatSurfaceFlux fux105 
/score/filter/particleWithKineticEnergy range105 1051.0 1061.0 keV gamma
/score/quantity/flatSurfaceFlux fux106 
/score/filter/particleWithKineticEnergy range106 1061.0 1071.0 keV gamma
/score/quantity/flatSurfaceFlux fux107 
/score/filter/particleWithKineticEnergy range107 1071.0 1081.0 keV gamma
/score/quantity/flatSurfaceFlux fux108 
/score/filter/particleWithKineticEnergy range108 1081.0 1091.0 keV gamma
/score/quantity/flatSurfaceFlux fux109 
/score/filter/particleWithKineticEnergy range109 1091.0 1101.0 keV gamma
/score/quantity/flatSurfaceFlux fux110 
/score/filter/particleWithKineticEnergy range110 1101.0 1111.0 keV gamma
/score/quantity/flatSurfaceFlux fux111 
/score/filter/particleWithKineticEnergy range111 1111.0 1121.0 keV gamma
/score/quantity/flatSurfaceFlux fux112 
/score/filter/particleWithKineticEnergy range112 1121.0 1131.0 keV gamma
/score/quantity/flatSurfaceFlux fux113 
/score/filter/particleWithKineticEnergy range113 1131.0 1141.0 keV gamma
/score/quantity/flatSurfaceFlux fux114 
/score/filter/particleWithKineticEnergy range114 1141.0 1151.0 keV gamma
/score/quantity/flatSurfaceFlux fux115 
/score/filter/particleWithKineticEnergy range115 1151.0 1161.0 keV gamma
/score/quantity/flatSurfaceFlux fux116 
/score/filter/particleWithKineticEnergy range116 1161.0 1171.0 keV gamma
/score/quantity/flatSurfaceFlux fux117 
/score/filter/particleWithKineticEnergy range117 1171.0 1181.0 keV gamma
/score/quantity/flatSurfaceFlux fux118 
/score/filter/particleWithKineticEnergy range118 1181.0 1191.0 keV gamma
/score/quantity/flatSurfaceFlux fux119 
/score/filter/particleWithKineticEnergy range119 1191.0 1201.0 keV gamma
/score/quantity/flatSurfaceFlux fux120 
/score/filter/particleWithKineticEnergy range120 1201.0 1211.0 keV gamma
/score/quantity/flatSurfaceFlux fux121 
/score/filter/particleWithKineticEnergy range121 1211.0 1221.0 keV gamma
/score/quantity/flatSurfaceFlux fux122 
/score/filter/particleWithKineticEnergy range122 1221.0 1231.0 keV gamma
/score/quantity/flatSurfaceFlux fux123 
/score/filter/particleWithKineticEnergy range123 1231.0 1241.0 keV gamma
/score/quantity/flatSurfaceFlux fux124 
/score/filter/particleWithKineticEnergy range124 1241.0 1251.0 keV gamma
/score/quantity/flatSurfaceFlux fux125 
/score/filter/particleWithKineticEnergy range125 1251.0 1261.0 keV gamma
/score/quantity/flatSurfaceFlux fux126 
/score/filter/particleWithKineticEnergy range126 1261.0 1271.0 keV gamma
/score/quantity/flatSurfaceFlux fux127 
/score/filter/particleWithKineticEnergy range127 1271.0 1281.0 keV gamma
/score/quantity/flatSurfaceFlux fux128 
/score/filter/particleWithKineticEnergy range128 1281.0 1291.0 keV gamma
/score/quantity/flatSurfaceFlux fux129 
/score/filter/particleWithKineticEnergy range129 1291.0 1301.0 keV gamma
/score/quantity/flatSurfaceFlux fux130 
/score/filter/particleWithKineticEnergy range130 1301.0 1311.0 keV gamma
/score/quantity/flatSurfaceFlux fux131 
/score/filter/particleWithKineticEnergy range131 1311.0 1321.0 keV gamma
/score/quantity/flatSurfaceFlux fux132 
/score/filter/particleWithKineticEnergy range132 1321.0 1331.0 keV gamma
/score/quantity/flatSurfaceFlux fux133 
/score/filter/particleWithKineticEnergy range133 1331.0 1341.0 keV gamma
/score/quantity/flatSurfaceFlux fux134 
/score/filter/particleWithKineticEnergy range134 1341.0 1351.0 keV gamma
/score/quantity/flatSurfaceFlux fux135 
/score/filter/particleWithKineticEnergy range135 1351.0 1361.0 keV gamma
/score/quantity/flatSurfaceFlux fux136 
/score/filter/particleWithKineticEnergy range136 1361.0 1371.0 keV gamma
/score/quantity/flatSurfaceFlux fux137 
/score/filter/particleWithKineticEnergy range137 1371.0 1381.0 keV gamma
/score/quantity/flatSurfaceFlux fux138 
/score/filter/particleWithKineticEnergy range138 1381.0 1391.0 keV gamma
/score/quantity/flatSurfaceFlux fux139 
/score/filter/particleWithKineticEnergy range139 1391.0 1401.0 keV gamma
/score/quantity/flatSurfaceFlux fux140 
/score/filter/particleWithKineticEnergy range140 1401.0 1411.0 keV gamma
/score/quantity/flatSurfaceFlux fux141 
/score/filter/particleWithKineticEnergy range141 1411.0 1421.0 keV gamma
/score/quantity/flatSurfaceFlux fux142 
/score/filter/particleWithKineticEnergy range142 1421.0 1431.0 keV gamma
/score/quantity/flatSurfaceFlux fux143 
/score/filter/particleWithKineticEnergy range143 1431.0 1441.0 keV gamma
/score/quantity/flatSurfaceFlux fux144 
/score/filter/particleWithKineticEnergy range144 1441.0 1451.0 keV gamma
/score/quantity/flatSurfaceFlux fux145 
/score/filter/particleWithKineticEnergy range145 1451.0 1461.0 keV gamma
/score/quantity/flatSurfaceFlux fux146 
/score/filter/particleWithKineticEnergy range146 1461.0 1471.0 keV gamma
/score/quantity/flatSurfaceFlux fux147 
/score/filter/particleWithKineticEnergy range147 1471.0 1481.0 keV gamma
/score/quantity/flatSurfaceFlux fux148 
/score/filter/particleWithKineticEnergy range148 1481.0 1491.0 keV gamma
/score/quantity/flatSurfaceFlux fux149 
/score/filter/particleWithKineticEnergy range149 1491.0 1502.0 keV gamma
/score/quantity/flatSurfaceFlux fux150 
/score/filter/particleWithKineticEnergy range150 1502.0 1512.0 keV gamma
/score/quantity/flatSurfaceFlux fux151 
/score/filter/particleWithKineticEnergy range151 1512.0 1522.0 keV gamma
/score/quantity/flatSurfaceFlux fux152 
/score/filter/particleWithKineticEnergy range152 1522.0 1532.0 keV gamma
/score/quantity/flatSurfaceFlux fux153 
/score/filter/particleWithKineticEnergy range153 1532.0 1542.0 keV gamma
/score/quantity/flatSurfaceFlux fux154 
/score/filter/particleWithKineticEnergy range154 1542.0 1552.0 keV gamma
/score/quantity/flatSurfaceFlux fux155 
/score/filter/particleWithKineticEnergy range155 1552.0 1562.0 keV gamma
/score/quantity/flatSurfaceFlux fux156 
/score/filter/particleWithKineticEnergy range156 1562.0 1572.0 keV gamma
/score/quantity/flatSurfaceFlux fux157 
/score/filter/particleWithKineticEnergy range157 1572.0 1582.0 keV gamma
/score/quantity/flatSurfaceFlux fux158 
/score/filter/particleWithKineticEnergy range158 1582.0 1592.0 keV gamma
/score/quantity/flatSurfaceFlux fux159 
/score/filter/particleWithKineticEnergy range159 1592.0 1602.0 keV gamma
/score/quantity/flatSurfaceFlux fux160 
/score/filter/particleWithKineticEnergy range160 1602.0 1612.0 keV gamma
/score/quantity/flatSurfaceFlux fux161 
/score/filter/particleWithKineticEnergy range161 1612.0 1622.0 keV gamma
/score/quantity/flatSurfaceFlux fux162 
/score/filter/particleWithKineticEnergy range162 1622.0 1632.0 keV gamma
/score/quantity/flatSurfaceFlux fux163 
/score/filter/particleWithKineticEnergy range163 1632.0 1642.0 keV gamma
/score/quantity/flatSurfaceFlux fux164 
/score/filter/particleWithKineticEnergy range164 1642.0 1652.0 keV gamma
/score/quantity/flatSurfaceFlux fux165 
/score/filter/particleWithKineticEnergy range165 1652.0 1662.0 keV gamma
/score/quantity/flatSurfaceFlux fux166 
/score/filter/particleWithKineticEnergy range166 1662.0 1672.0 keV gamma
/score/quantity/flatSurfaceFlux fux167 
/score/filter/particleWithKineticEnergy range167 1672.0 1682.0 keV gamma
/score/quantity/flatSurfaceFlux fux168 
/score/filter/particleWithKineticEnergy range168 1682.0 1692.0 keV gamma
/score/quantity/flatSurfaceFlux fux169 
/score/filter/particleWithKineticEnergy range169 1692.0 1702.0 keV gamma
/score/quantity/flatSurfaceFlux fux170 
/score/filter/particleWithKineticEnergy range170 1702.0 1712.0 keV gamma
/score/quantity/flatSurfaceFlux fux171 
/score/filter/particleWithKineticEnergy range171 1712.0 1722.0 keV gamma
/score/quantity/flatSurfaceFlux fux172 
/score/filter/particleWithKineticEnergy range172 1722.0 1732.0 keV gamma
/score/quantity/flatSurfaceFlux fux173 
/score/filter/particleWithKineticEnergy range173 1732.0 1742.0 keV gamma
/score/quantity/flatSurfaceFlux fux174 
/score/filter/particleWithKineticEnergy range174 1742.0 1752.0 keV gamma
/score/quantity/flatSurfaceFlux fux175 
/score/filter/particleWithKineticEnergy range175 1752.0 1762.0 keV gamma
/score/quantity/flatSurfaceFlux fux176 
/score/filter/particleWithKineticEnergy range176 1762.0 1772.0 keV gamma
/score/quantity/flatSurfaceFlux fux177 
/score/filter/particleWithKineticEnergy range177 1772.0 1782.0 keV gamma
/score/quantity/flatSurfaceFlux fux178 
/score/filter/particleWithKineticEnergy range178 1782.0 1792.0 keV gamma
/score/quantity/flatSurfaceFlux fux179 
/score/filter/particleWithKineticEnergy range179 1792.0 1802.0 keV gamma
/score/quantity/flatSurfaceFlux fux180 
/score/filter/particleWithKineticEnergy range180 1802.0 1812.0 keV gamma
/score/quantity/flatSurfaceFlux fux181 
/score/filter/particleWithKineticEnergy range181 1812.0 1822.0 keV gamma
/score/quantity/flatSurfaceFlux fux182 
/score/filter/particleWithKineticEnergy range182 1822.0 1832.0 keV gamma
/score/quantity/flatSurfaceFlux fux183 
/score/filter/particleWithKineticEnergy range183 1832.0 1842.0 keV gamma
/score/quantity/flatSurfaceFlux fux184 
/score/filter/particleWithKineticEnergy range184 1842.0 1852.0 keV gamma
/score/quantity/flatSurfaceFlux fux185 
/score/filter/particleWithKineticEnergy range185 1852.0 1862.0 keV gamma
/score/quantity/flatSurfaceFlux fux186 
/score/filter/particleWithKineticEnergy range186 1862.0 1872.0 keV gamma
/score/quantity/flatSurfaceFlux fux187 
/score/filter/particleWithKineticEnergy range187 1872.0 1882.0 keV gamma
/score/quantity/flatSurfaceFlux fux188 
/score/filter/particleWithKineticEnergy range188 1882.0 1892.0 keV gamma
/score/quantity/flatSurfaceFlux fux189 
/score/filter/particleWithKineticEnergy range189 1892.0 1902.0 keV gamma
/score/quantity/flatSurfaceFlux fux190 
/score/filter/particleWithKineticEnergy range190 1902.0 1912.0 keV gamma
/score/quantity/flatSurfaceFlux fux191 
/score/filter/particleWithKineticEnergy range191 1912.0 1922.0 keV gamma
/score/quantity/flatSurfaceFlux fux192 
/score/filter/particleWithKineticEnergy range192 1922.0 1932.0 keV gamma
/score/quantity/flatSurfaceFlux fux193 
/score/filter/particleWithKineticEnergy range193 1932.0 1942.0 keV gamma
/score/quantity/flatSurfaceFlux fux194 
/score/filter/particleWithKineticEnergy range194 1942.0 1952.0 keV gamma
/score/quantity/flatSurfaceFlux fux195 
/score/filter/particleWithKineticEnergy range195 1952.0 1962.0 keV gamma
/score/quantity/flatSurfaceFlux fux196 
/score/filter/particleWithKineticEnergy range196 1962.0 1972.0 keV gamma
/score/quantity/flatSurfaceFlux fux197 
/score/filter/particleWithKineticEnergy range197 1972.0 1982.0 keV gamma
/score/quantity/flatSurfaceFlux fux198 
/score/filter/particleWithKineticEnergy range198 1982.0 1992.0 keV gamma
/score/quantity/flatSurfaceFlux fux199 
/score/filter/particleWithKineticEnergy range199 1992.0 2002.0 keV gamma
/score/quantity/flatSurfaceFlux fux200 
/score/filter/particleWithKineticEnergy range200 2002.0 2012.0 keV gamma
/score/quantity/flatSurfaceFlux fux201 
/score/filter/particleWithKineticEnergy range201 2012.0 2022.0 keV gamma
/score/quantity/flatSurfaceFlux fux202 
/score/filter/particleWithKineticEnergy range202 2022.0 2032.0 keV gamma
/score/quantity/flatSurfaceFlux fux203 
/score/filter/particleWithKineticEnergy range203 2032.0 2042.0 keV gamma
/score/quantity/flatSurfaceFlux fux204 
/score/filter/particleWithKineticEnergy range204 2042.0 2052.0 keV gamma
/score/quantity/flatSurfaceFlux fux205 
/score/filter/particleWithKineticEnergy range205 2052.0 2062.0 keV gamma
/score/quantity/flatSurfaceFlux fux206 
/score/filter/particleWithKineticEnergy range206 2062.0 2072.0 keV gamma
/score/quantity/flatSurfaceFlux fux207 
/score/filter/particleWithKineticEnergy range207 2072.0 2082.0 keV gamma
/score/quantity/flatSurfaceFlux fux208 
/score/filter/particleWithKineticEnergy range208 2082.0 2092.0 keV gamma
/score/quantity/flatSurfaceFlux fux209 
/score/filter/particleWithKineticEnergy range209 2092.0 2102.0 keV gamma
/score/quantity/flatSurfaceFlux fux210 
/score/filter/particleWithKineticEnergy range210 2102.0 2112.0 keV gamma
/score/quantity/flatSurfaceFlux fux211 
/score/filter/particleWithKineticEnergy range211 2112.0 2122.0 keV gamma
/score/quantity/flatSurfaceFlux fux212 
/score/filter/particleWithKineticEnergy range212 2122.0 2132.0 keV gamma
/score/quantity/flatSurfaceFlux fux213 
/score/filter/particleWithKineticEnergy range213 2132.0 2142.0 keV gamma
/score/quantity/flatSurfaceFlux fux214 
/score/filter/particleWithKineticEnergy range214 2142.0 2152.0 keV gamma
/score/quantity/flatSurfaceFlux fux215 
/score/filter/particleWithKineticEnergy range215 2152.0 2162.0 keV gamma
/score/quantity/flatSurfaceFlux fux216 
/score/filter/particleWithKineticEnergy range216 2162.0 2172.0 keV gamma
/score/quantity/flatSurfaceFlux fux217 
/score/filter/particleWithKineticEnergy range217 2172.0 2182.0 keV gamma
/score/quantity/flatSurfaceFlux fux218 
/score/filter/particleWithKineticEnergy range218 2182.0 2192.0 keV gamma
/score/quantity/flatSurfaceFlux fux219 
/score/filter/particleWithKineticEnergy range219 2192.0 2202.0 keV gamma
/score/quantity/flatSurfaceFlux fux220 
/score/filter/particleWithKineticEnergy range220 2202.0 2212.0 keV gamma
/score/quantity/flatSurfaceFlux fux221 
/score/filter/particleWithKineticEnergy range221 2212.0 2222.0 keV gamma
/score/quantity/flatSurfaceFlux fux222 
/score/filter/particleWithKineticEnergy range222 2222.0 2232.0 keV gamma
/score/quantity/flatSurfaceFlux fux223 
/score/filter/particleWithKineticEnergy range223 2232.0 2242.0 keV gamma
/score/quantity/flatSurfaceFlux fux224 
/score/filter/particleWithKineticEnergy range224 2242.0 2252.0 keV gamma
/score/quantity/flatSurfaceFlux fux225 
/score/filter/particleWithKineticEnergy range225 2252.0 2262.0 keV gamma
/score/quantity/flatSurfaceFlux fux226 
/score/filter/particleWithKineticEnergy range226 2262.0 2272.0 keV gamma
/score/quantity/flatSurfaceFlux fux227 
/score/filter/particleWithKineticEnergy range227 2272.0 2282.0 keV gamma
/score/quantity/flatSurfaceFlux fux228 
/score/filter/particleWithKineticEnergy range228 2282.0 2292.0 keV gamma
/score/quantity/flatSurfaceFlux fux229 
/score/filter/particleWithKineticEnergy range229 2292.0 2302.0 keV gamma
/score/quantity/flatSurfaceFlux fux230 
/score/filter/particleWithKineticEnergy range230 2302.0 2312.0 keV gamma
/score/quantity/flatSurfaceFlux fux231 
/score/filter/particleWithKineticEnergy range231 2312.0 2322.0 keV gamma
/score/quantity/flatSurfaceFlux fux232 
/score/filter/particleWithKineticEnergy range232 2322.0 2332.0 keV gamma
/score/quantity/flatSurfaceFlux fux233 
/score/filter/particleWithKineticEnergy range233 2332.0 2342.0 keV gamma
/score/quantity/flatSurfaceFlux fux234 
/score/filter/particleWithKineticEnergy range234 2342.0 2352.0 keV gamma
/score/quantity/flatSurfaceFlux fux235 
/score/filter/particleWithKineticEnergy range235 2352.0 2362.0 keV gamma
/score/quantity/flatSurfaceFlux fux236 
/score/filter/particleWithKineticEnergy range236 2362.0 2372.0 keV gamma
/score/quantity/flatSurfaceFlux fux237 
/score/filter/particleWithKineticEnergy range237 2372.0 2382.0 keV gamma
/score/quantity/flatSurfaceFlux fux238 
/score/filter/particleWithKineticEnergy range238 2382.0 2392.0 keV gamma
/score/quantity/flatSurfaceFlux fux239 
/score/filter/particleWithKineticEnergy range239 2392.0 2402.0 keV gamma
/score/quantity/flatSurfaceFlux fux240 
/score/filter/particleWithKineticEnergy range240 2402.0 2412.0 keV gamma
/score/quantity/flatSurfaceFlux fux241 
/score/filter/particleWithKineticEnergy range241 2412.0 2422.0 keV gamma
/score/quantity/flatSurfaceFlux fux242 
/score/filter/particleWithKineticEnergy range242 2422.0 2432.0 keV gamma
/score/quantity/flatSurfaceFlux fux243 
/score/filter/particleWithKineticEnergy range243 2432.0 2442.0 keV gamma
/score/quantity/flatSurfaceFlux fux244 
/score/filter/particleWithKineticEnergy range244 2442.0 2452.0 keV gamma
/score/quantity/flatSurfaceFlux fux245 
/score/filter/particleWithKineticEnergy range245 2452.0 2462.0 keV gamma
/score/quantity/flatSurfaceFlux fux246 
/score/filter/particleWithKineticEnergy range246 2462.0 2472.0 keV gamma
/score/quantity/flatSurfaceFlux fux247 
/score/filter/particleWithKineticEnergy range247 2472.0 2482.0 keV gamma
/score/quantity/flatSurfaceFlux fux248 
/score/filter/particleWithKineticEnergy range248 2482.0 2492.0 keV gamma
/score/quantity/flatSurfaceFlux fux249 
/score/filter/particleWithKineticEnergy range249 2492.0 2503.0 keV gamma
/score/quantity/flatSurfaceFlux fux250 
/score/filter/particleWithKineticEnergy range250 2503.0 2513.0 keV gamma
/score/quantity/flatSurfaceFlux fux251 
/score/filter/particleWithKineticEnergy range251 2513.0 2523.0 keV gamma
/score/quantity/flatSurfaceFlux fux252 
/score/filter/particleWithKineticEnergy range252 2523.0 2533.0 keV gamma
/score/quantity/flatSurfaceFlux fux253 
/score/filter/particleWithKineticEnergy range253 2533.0 2543.0 keV gamma
/score/quantity/flatSurfaceFlux fux254 
/score/filter/particleWithKineticEnergy range254 2543.0 2553.0 keV gamma
/score/quantity/flatSurfaceFlux fux255 
/score/filter/particleWithKineticEnergy range255 2553.0 2563.0 keV gamma
/score/quantity/flatSurfaceFlux fux256 
/score/filter/particleWithKineticEnergy range256 2563.0 2573.0 keV gamma
/score/quantity/flatSurfaceFlux fux257 
/score/filter/particleWithKineticEnergy range257 2573.0 2583.0 keV gamma
/score/quantity/flatSurfaceFlux fux258 
/score/filter/particleWithKineticEnergy range258 2583.0 2593.0 keV gamma
/score/quantity/flatSurfaceFlux fux259 
/score/filter/particleWithKineticEnergy range259 2593.0 2603.0 keV gamma
/score/quantity/flatSurfaceFlux fux260 
/score/filter/particleWithKineticEnergy range260 2603.0 2613.0 keV gamma
/score/quantity/flatSurfaceFlux fux261 
/score/filter/particleWithKineticEnergy range261 2613.0 2623.0 keV gamma
/score/quantity/flatSurfaceFlux fux262 
/score/filter/particleWithKineticEnergy range262 2623.0 2633.0 keV gamma
/score/quantity/flatSurfaceFlux fux263 
/score/filter/particleWithKineticEnergy range263 2633.0 2643.0 keV gamma
/score/quantity/flatSurfaceFlux fux264 
/score/filter/particleWithKineticEnergy range264 2643.0 2653.0 keV gamma
/score/quantity/flatSurfaceFlux fux265 
/score/filter/particleWithKineticEnergy range265 2653.0 2663.0 keV gamma
/score/quantity/flatSurfaceFlux fux266 
/score/filter/particleWithKineticEnergy range266 2663.0 2673.0 keV gamma
/score/quantity/flatSurfaceFlux fux267 
/score/filter/particleWithKineticEnergy range267 2673.0 2683.0 keV gamma
/score/quantity/flatSurfaceFlux fux268 
/score/filter/particleWithKineticEnergy range268 2683.0 2693.0 keV gamma
/score/quantity/flatSurfaceFlux fux269 
/score/filter/particleWithKineticEnergy range269 2693.0 2703.0 keV gamma
/score/quantity/flatSurfaceFlux fux270 
/score/filter/particleWithKineticEnergy range270 2703.0 2713.0 keV gamma
/score/quantity/flatSurfaceFlux fux271 
/score/filter/particleWithKineticEnergy range271 2713.0 2723.0 keV gamma
/score/quantity/flatSurfaceFlux fux272 
/score/filter/particleWithKineticEnergy range272 2723.0 2733.0 keV gamma
/score/quantity/flatSurfaceFlux fux273 
/score/filter/particleWithKineticEnergy range273 2733.0 2743.0 keV gamma
/score/quantity/flatSurfaceFlux fux274 
/score/filter/particleWithKineticEnergy range274 2743.0 2753.0 keV gamma
/score/quantity/flatSurfaceFlux fux275 
/score/filter/particleWithKineticEnergy range275 2753.0 2763.0 keV gamma
/score/quantity/flatSurfaceFlux fux276 
/score/filter/particleWithKineticEnergy range276 2763.0 2773.0 keV gamma
/score/quantity/flatSurfaceFlux fux277 
/score/filter/particleWithKineticEnergy range277 2773.0 2783.0 keV gamma
/score/quantity/flatSurfaceFlux fux278 
/score/filter/particleWithKineticEnergy range278 2783.0 2793.0 keV gamma
/score/quantity/flatSurfaceFlux fux279 
/score/filter/particleWithKineticEnergy range279 2793.0 2803.0 keV gamma
/score/quantity/flatSurfaceFlux fux280 
/score/filter/particleWithKineticEnergy range280 2803.0 2813.0 keV gamma
/score/quantity/flatSurfaceFlux fux281 
/score/filter/particleWithKineticEnergy range281 2813.0 2823.0 keV gamma
/score/quantity/flatSurfaceFlux fux282 
/score/filter/particleWithKineticEnergy range282 2823.0 2833.0 keV gamma
/score/quantity/flatSurfaceFlux fux283 
/score/filter/particleWithKineticEnergy range283 2833.0 2843.0 keV gamma
/score/quantity/flatSurfaceFlux fux284 
/score/filter/particleWithKineticEnergy range284 2843.0 2853.0 keV gamma
/score/quantity/flatSurfaceFlux fux285 
/score/filter/particleWithKineticEnergy range285 2853.0 2863.0 keV gamma
/score/quantity/flatSurfaceFlux fux286 
/score/filter/particleWithKineticEnergy range286 2863.0 2873.0 keV gamma
/score/quantity/flatSurfaceFlux fux287 
/score/filter/particleWithKineticEnergy range287 2873.0 2883.0 keV gamma
/score/quantity/flatSurfaceFlux fux288 
/score/filter/particleWithKineticEnergy range288 2883.0 2893.0 keV gamma
/score/quantity/flatSurfaceFlux fux289 
/score/filter/particleWithKineticEnergy range289 2893.0 2903.0 keV gamma
/score/quantity/flatSurfaceFlux fux290 
/score/filter/particleWithKineticEnergy range290 2903.0 2913.0 keV gamma
/score/quantity/flatSurfaceFlux fux291 
/score/filter/particleWithKineticEnergy range291 2913.0 2923.0 keV gamma
/score/quantity/flatSurfaceFlux fux292 
/score/filter/particleWithKineticEnergy range292 2923.0 2933.0 keV gamma
/score/quantity/flatSurfaceFlux fux293 
/score/filter/particleWithKineticEnergy range293 2933.0 2943.0 keV gamma
/score/quantity/flatSurfaceFlux fux294 
/score/filter/particleWithKineticEnergy range294 2943.0 2953.0 keV gamma
/score/quantity/flatSurfaceFlux fux295 
/score/filter/particleWithKineticEnergy range295 2953.0 2963.0 keV gamma
/score/quantity/flatSurfaceFlux fux296 
/score/filter/particleWithKineticEnergy range296 2963.0 2973.0 keV gamma
/score/quantity/flatSurfaceFlux fux297 
/score/filter/particleWithKineticEnergy range297 2973.0 2983.0 keV gamma
/score/quantity/flatSurfaceFlux fux298 
/score/filter/particleWithKineticEnergy range298 2983.0 2993.0 keV gamma
/score/quantity/flatSurfaceFlux fux299 
/score/filter/particleWithKineticEnergy range299 2993.0 3003.0 keV gamma
/score/quantity/flatSurfaceFlux fux300 
/score/filter/particleWithKineticEnergy range300 3003.0 3013.0 keV gamma
/score/quantity/flatSurfaceFlux fux301 
/score/filter/particleWithKineticEnergy range301 3013.0 3023.0 keV gamma
/score/quantity/flatSurfaceFlux fux302 
/score/filter/particleWithKineticEnergy range302 3023.0 3033.0 keV gamma
/score/quantity/flatSurfaceFlux fux303 
/score/filter/particleWithKineticEnergy range303 3033.0 3043.0 keV gamma
/score/quantity/flatSurfaceFlux fux304 
/score/filter/particleWithKineticEnergy range304 3043.0 3053.0 keV gamma
/score/quantity/flatSurfaceFlux fux305 
/score/filter/particleWithKineticEnergy range305 3053.0 3063.0 keV gamma
/score/quantity/flatSurfaceFlux fux306 
/score/filter/particleWithKineticEnergy range306 3063.0 3073.0 keV gamma
/score/quantity/flatSurfaceFlux fux307 
/score/filter/particleWithKineticEnergy range307 3073.0 3083.0 keV gamma
/score/quantity/flatSurfaceFlux fux308 
/score/filter/particleWithKineticEnergy range308 3083.0 3093.0 keV gamma
/score/quantity/flatSurfaceFlux fux309 
/score/filter/particleWithKineticEnergy range309 3093.0 3103.0 keV gamma
/score/quantity/flatSurfaceFlux fux310 
/score/filter/particleWithKineticEnergy range310 3103.0 3113.0 keV gamma
/score/quantity/flatSurfaceFlux fux311 
/score/filter/particleWithKineticEnergy range311 3113.0 3123.0 keV gamma
/score/quantity/flatSurfaceFlux fux312 
/score/filter/particleWithKineticEnergy range312 3123.0 3133.0 keV gamma
/score/quantity/flatSurfaceFlux fux313 
/score/filter/particleWithKineticEnergy range313 3133.0 3143.0 keV gamma
/score/quantity/flatSurfaceFlux fux314 
/score/filter/particleWithKineticEnergy range314 3143.0 3153.0 keV gamma
/score/quantity/flatSurfaceFlux fux315 
/score/filter/particleWithKineticEnergy range315 3153.0 3163.0 keV gamma
/score/quantity/flatSurfaceFlux fux316 
/score/filter/particleWithKineticEnergy range316 3163.0 3173.0 keV gamma
/score/quantity/flatSurfaceFlux fux317 
/score/filter/particleWithKineticEnergy range317 3173.0 3183.0 keV gamma
/score/quantity/flatSurfaceFlux fux318 
/score/filter/particleWithKineticEnergy range318 3183.0 3193.0 keV gamma
/score/quantity/flatSurfaceFlux fux319 
/score/filter/particleWithKineticEnergy range319 3193.0 3203.0 keV gamma
/score/quantity/flatSurfaceFlux fux320 
/score/filter/particleWithKineticEnergy range320 3203.0 3213.0 keV gamma
/score/quantity/flatSurfaceFlux fux321 
/score/filter/particleWithKineticEnergy range321 3213.0 3223.0 keV gamma
/score/quantity/flatSurfaceFlux fux322 
/score/filter/particleWithKineticEnergy range322 3223.0 3233.0 keV gamma
/score/quantity/flatSurfaceFlux fux323 
/score/filter/particleWithKineticEnergy range323 3233.0 3243.0 keV gamma
/score/quantity/flatSurfaceFlux fux324 
/score/filter/particleWithKineticEnergy range324 3243.0 3253.0 keV gamma
/score/quantity/flatSurfaceFlux fux325 
/score/filter/particleWithKineticEnergy range325 3253.0 3263.0 keV gamma
/score/quantity/flatSurfaceFlux fux326 
/score/filter/particleWithKineticEnergy range326 3263.0 3273.0 keV gamma
/score/quantity/flatSurfaceFlux fux327 
/score/filter/particleWithKineticEnergy range327 3273.0 3283.0 keV gamma
/score/quantity/flatSurfaceFlux fux328 
/score/filter/particleWithKineticEnergy range328 3283.0 3293.0 keV gamma
/score/quantity/flatSurfaceFlux fux329 
/score/filter/particleWithKineticEnergy range329 3293.0 3303.0 keV gamma
/score/quantity/flatSurfaceFlux fux330 
/score/filter/particleWithKineticEnergy range330 3303.0 3313.0 keV gamma
/score/quantity/flatSurfaceFlux fux331 
/score/filter/particleWithKineticEnergy range331 3313.0 3323.0 keV gamma
/score/quantity/flatSurfaceFlux fux332 
/score/filter/particleWithKineticEnergy range332 3323.0 3333.0 keV gamma
/score/quantity/flatSurfaceFlux fux333 
/score/filter/particleWithKineticEnergy range333 3333.0 3343.0 keV gamma
/score/quantity/flatSurfaceFlux fux334 
/score/filter/particleWithKineticEnergy range334 3343.0 3353.0 keV gamma
/score/quantity/flatSurfaceFlux fux335 
/score/filter/particleWithKineticEnergy range335 3353.0 3363.0 keV gamma
/score/quantity/flatSurfaceFlux fux336 
/score/filter/particleWithKineticEnergy range336 3363.0 3373.0 keV gamma
/score/quantity/flatSurfaceFlux fux337 
/score/filter/particleWithKineticEnergy range337 3373.0 3383.0 keV gamma
/score/quantity/flatSurfaceFlux fux338 
/score/filter/particleWithKineticEnergy range338 3383.0 3393.0 keV gamma
/score/quantity/flatSurfaceFlux fux339 
/score/filter/particleWithKineticEnergy range339 3393.0 3403.0 keV gamma
/score/quantity/flatSurfaceFlux fux340 
/score/filter/particleWithKineticEnergy range340 3403.0 3413.0 keV gamma
/score/quantity/flatSurfaceFlux fux341 
/score/filter/particleWithKineticEnergy range341 3413.0 3423.0 keV gamma
/score/quantity/flatSurfaceFlux fux342 
/score/filter/particleWithKineticEnergy range342 3423.0 3433.0 keV gamma
/score/quantity/flatSurfaceFlux fux343 
/score/filter/particleWithKineticEnergy range343 3433.0 3443.0 keV gamma
/score/quantity/flatSurfaceFlux fux344 
/score/filter/particleWithKineticEnergy range344 3443.0 3453.0 keV gamma
/score/quantity/flatSurfaceFlux fux345 
/score/filter/particleWithKineticEnergy range345 3453.0 3463.0 keV gamma
/score/quantity/flatSurfaceFlux fux346 
/score/filter/particleWithKineticEnergy range346 3463.0 3473.0 keV gamma
/score/quantity/flatSurfaceFlux fux347 
/score/filter/particleWithKineticEnergy range347 3473.0 3483.0 keV gamma
/score/quantity/flatSurfaceFlux fux348 
/score/filter/particleWithKineticEnergy range348 3483.0 3493.0 keV gamma
/score/quantity/flatSurfaceFlux fux349 
/score/filter/particleWithKineticEnergy range349 3493.0 3504.0 keV gamma
/score/quantity/flatSurfaceFlux fux350 
/score/filter/particleWithKineticEnergy range350 3504.0 3514.0 keV gamma
/score/quantity/flatSurfaceFlux fux351 
/score/filter/particleWithKineticEnergy range351 3514.0 3524.0 keV gamma
/score/quantity/flatSurfaceFlux fux352 
/score/filter/particleWithKineticEnergy range352 3524.0 3534.0 keV gamma
/score/quantity/flatSurfaceFlux fux353 
/score/filter/particleWithKineticEnergy range353 3534.0 3544.0 keV gamma
/score/quantity/flatSurfaceFlux fux354 
/score/filter/particleWithKineticEnergy range354 3544.0 3554.0 keV gamma
/score/quantity/flatSurfaceFlux fux355 
/score/filter/particleWithKineticEnergy range355 3554.0 3564.0 keV gamma
/score/quantity/flatSurfaceFlux fux356 
/score/filter/particleWithKineticEnergy range356 3564.0 3574.0 keV gamma
/score/quantity/flatSurfaceFlux fux357 
/score/filter/particleWithKineticEnergy range357 3574.0 3584.0 keV gamma
/score/quantity/flatSurfaceFlux fux358 
/score/filter/particleWithKineticEnergy range358 3584.0 3594.0 keV gamma
/score/quantity/flatSurfaceFlux fux359 
/score/filter/particleWithKineticEnergy range359 3594.0 3604.0 keV gamma
/score/quantity/flatSurfaceFlux fux360 
/score/filter/particleWithKineticEnergy range360 3604.0 3614.0 keV gamma
/score/quantity/flatSurfaceFlux fux361 
/score/filter/particleWithKineticEnergy range361 3614.0 3624.0 keV gamma
/score/quantity/flatSurfaceFlux fux362 
/score/filter/particleWithKineticEnergy range362 3624.0 3634.0 keV gamma
/score/quantity/flatSurfaceFlux fux363 
/score/filter/particleWithKineticEnergy range363 3634.0 3644.0 keV gamma
/score/quantity/flatSurfaceFlux fux364 
/score/filter/particleWithKineticEnergy range364 3644.0 3654.0 keV gamma
/score/quantity/flatSurfaceFlux fux365 
/score/filter/particleWithKineticEnergy range365 3654.0 3664.0 keV gamma
/score/quantity/flatSurfaceFlux fux366 
/score/filter/particleWithKineticEnergy range366 3664.0 3674.0 keV gamma
/score/quantity/flatSurfaceFlux fux367 
/score/filter/particleWithKineticEnergy range367 3674.0 3684.0 keV gamma
/score/quantity/flatSurfaceFlux fux368 
/score/filter/particleWithKineticEnergy range368 3684.0 3694.0 keV gamma
/score/quantity/flatSurfaceFlux fux369 
/score/filter/particleWithKineticEnergy range369 3694.0 3704.0 keV gamma
/score/quantity/flatSurfaceFlux fux370 
/score/filter/particleWithKineticEnergy range370 3704.0 3714.0 keV gamma
/score/quantity/flatSurfaceFlux fux371 
/score/filter/particleWithKineticEnergy range371 3714.0 3724.0 keV gamma
/score/quantity/flatSurfaceFlux fux372 
/score/filter/particleWithKineticEnergy range372 3724.0 3734.0 keV gamma
/score/quantity/flatSurfaceFlux fux373 
/score/filter/particleWithKineticEnergy range373 3734.0 3744.0 keV gamma
/score/quantity/flatSurfaceFlux fux374 
/score/filter/particleWithKineticEnergy range374 3744.0 3754.0 keV gamma
/score/quantity/flatSurfaceFlux fux375 
/score/filter/particleWithKineticEnergy range375 3754.0 3764.0 keV gamma
/score/quantity/flatSurfaceFlux fux376 
/score/filter/particleWithKineticEnergy range376 3764.0 3774.0 keV gamma
/score/quantity/flatSurfaceFlux fux377 
/score/filter/particleWithKineticEnergy range377 3774.0 3784.0 keV gamma
/score/quantity/flatSurfaceFlux fux378 
/score/filter/particleWithKineticEnergy range378 3784.0 3794.0 keV gamma
/score/quantity/flatSurfaceFlux fux379 
/score/filter/particleWithKineticEnergy range379 3794.0 3804.0 keV gamma
/score/quantity/flatSurfaceFlux fux380 
/score/filter/particleWithKineticEnergy range380 3804.0 3814.0 keV gamma
/score/quantity/flatSurfaceFlux fux381 
/score/filter/particleWithKineticEnergy range381 3814.0 3824.0 keV gamma
/score/quantity/flatSurfaceFlux fux382 
/score/filter/particleWithKineticEnergy range382 3824.0 3834.0 keV gamma
/score/quantity/flatSurfaceFlux fux383 
/score/filter/particleWithKineticEnergy range383 3834.0 3844.0 keV gamma
/score/quantity/flatSurfaceFlux fux384 
/score/filter/particleWithKineticEnergy range384 3844.0 3854.0 keV gamma
/score/quantity/flatSurfaceFlux fux385 
/score/filter/particleWithKineticEnergy range385 3854.0 3864.0 keV gamma
/score/quantity/flatSurfaceFlux fux386 
/score/filter/particleWithKineticEnergy range386 3864.0 3874.0 keV gamma
/score/quantity/flatSurfaceFlux fux387 
/score/filter/particleWithKineticEnergy range387 3874.0 3884.0 keV gamma
/score/quantity/flatSurfaceFlux fux388 
/score/filter/particleWithKineticEnergy range388 3884.0 3894.0 keV gamma
/score/quantity/flatSurfaceFlux fux389 
/score/filter/particleWithKineticEnergy range389 3894.0 3904.0 keV gamma
/score/quantity/flatSurfaceFlux fux390 
/score/filter/particleWithKineticEnergy range390 3904.0 3914.0 keV gamma
/score/quantity/flatSurfaceFlux fux391 
/score/filter/particleWithKineticEnergy range391 3914.0 3924.0 keV gamma
/score/quantity/flatSurfaceFlux fux392 
/score/filter/particleWithKineticEnergy range392 3924.0 3934.0 keV gamma
/score/quantity/flatSurfaceFlux fux393 
/score/filter/particleWithKineticEnergy range393 3934.0 3944.0 keV gamma
/score/quantity/flatSurfaceFlux fux394 
/score/filter/particleWithKineticEnergy range394 3944.0 3954.0 keV gamma
/score/quantity/flatSurfaceFlux fux395 
/score/filter/particleWithKineticEnergy range395 3954.0 3964.0 keV gamma
/score/quantity/flatSurfaceFlux fux396 
/score/filter/particleWithKineticEnergy range396 3964.0 3974.0 keV gamma
/score/quantity/flatSurfaceFlux fux397 
/score/filter/particleWithKineticEnergy range397 3974.0 3984.0 keV gamma
/score/quantity/flatSurfaceFlux fux398 
/score/filter/particleWithKineticEnergy range398 3984.0 3994.0 keV gamma
/score/quantity/flatSurfaceFlux fux399 
/score/filter/particleWithKineticEnergy range399 3994.0 4004.0 keV gamma
/score/quantity/flatSurfaceFlux fux400 
/score/filter/particleWithKineticEnergy range400 4004.0 4014.0 keV gamma
/score/quantity/flatSurfaceFlux fux401 
/score/filter/particleWithKineticEnergy range401 4014.0 4024.0 keV gamma
/score/quantity/flatSurfaceFlux fux402 
/score/filter/particleWithKineticEnergy range402 4024.0 4034.0 keV gamma
/score/quantity/flatSurfaceFlux fux403 
/score/filter/particleWithKineticEnergy range403 4034.0 4044.0 keV gamma
/score/quantity/flatSurfaceFlux fux404 
/score/filter/particleWithKineticEnergy range404 4044.0 4054.0 keV gamma
/score/quantity/flatSurfaceFlux fux405 
/score/filter/particleWithKineticEnergy range405 4054.0 4064.0 keV gamma
/score/quantity/flatSurfaceFlux fux406 
/score/filter/particleWithKineticEnergy range406 4064.0 4074.0 keV gamma
/score/quantity/flatSurfaceFlux fux407 
/score/filter/particleWithKineticEnergy range407 4074.0 4084.0 keV gamma
/score/quantity/flatSurfaceFlux fux408 
/score/filter/particleWithKineticEnergy range408 4084.0 4094.0 keV gamma
/score/quantity/flatSurfaceFlux fux409 
/score/filter/particleWithKineticEnergy range409 4094.0 4104.0 keV gamma
/score/quantity/flatSurfaceFlux fux410 
/score/filter/particleWithKineticEnergy range410 4104.0 4114.0 keV gamma
/score/quantity/flatSurfaceFlux fux411 
/score/filter/particleWithKineticEnergy range411 4114.0 4124.0 keV gamma
/score/quantity/flatSurfaceFlux fux412 
/score/filter/particleWithKineticEnergy range412 4124.0 4134.0 keV gamma
/score/quantity/flatSurfaceFlux fux413 
/score/filter/particleWithKineticEnergy range413 4134.0 4144.0 keV gamma
/score/quantity/flatSurfaceFlux fux414 
/score/filter/particleWithKineticEnergy range414 4144.0 4154.0 keV gamma
/score/quantity/flatSurfaceFlux fux415 
/score/filter/particleWithKineticEnergy range415 4154.0 4164.0 keV gamma
/score/quantity/flatSurfaceFlux fux416 
/score/filter/particleWithKineticEnergy range416 4164.0 4174.0 keV gamma
/score/quantity/flatSurfaceFlux fux417 
/score/filter/particleWithKineticEnergy range417 4174.0 4184.0 keV gamma
/score/quantity/flatSurfaceFlux fux418 
/score/filter/particleWithKineticEnergy range418 4184.0 4194.0 keV gamma
/score/quantity/flatSurfaceFlux fux419 
/score/filter/particleWithKineticEnergy range419 4194.0 4204.0 keV gamma
/score/quantity/flatSurfaceFlux fux420 
/score/filter/particleWithKineticEnergy range420 4204.0 4214.0 keV gamma
/score/quantity/flatSurfaceFlux fux421 
/score/filter/particleWithKineticEnergy range421 4214.0 4224.0 keV gamma
/score/quantity/flatSurfaceFlux fux422 
/score/filter/particleWithKineticEnergy range422 4224.0 4234.0 keV gamma
/score/quantity/flatSurfaceFlux fux423 
/score/filter/particleWithKineticEnergy range423 4234.0 4244.0 keV gamma
/score/quantity/flatSurfaceFlux fux424 
/score/filter/particleWithKineticEnergy range424 4244.0 4254.0 keV gamma
/score/quantity/flatSurfaceFlux fux425 
/score/filter/particleWithKineticEnergy range425 4254.0 4264.0 keV gamma
/score/quantity/flatSurfaceFlux fux426 
/score/filter/particleWithKineticEnergy range426 4264.0 4274.0 keV gamma
/score/quantity/flatSurfaceFlux fux427 
/score/filter/particleWithKineticEnergy range427 4274.0 4284.0 keV gamma
/score/quantity/flatSurfaceFlux fux428 
/score/filter/particleWithKineticEnergy range428 4284.0 4294.0 keV gamma
/score/quantity/flatSurfaceFlux fux429 
/score/filter/particleWithKineticEnergy range429 4294.0 4304.0 keV gamma
/score/quantity/flatSurfaceFlux fux430 
/score/filter/particleWithKineticEnergy range430 4304.0 4314.0 keV gamma
/score/quantity/flatSurfaceFlux fux431 
/score/filter/particleWithKineticEnergy range431 4314.0 4324.0 keV gamma
/score/quantity/flatSurfaceFlux fux432 
/score/filter/particleWithKineticEnergy range432 4324.0 4334.0 keV gamma
/score/quantity/flatSurfaceFlux fux433 
/score/filter/particleWithKineticEnergy range433 4334.0 4344.0 keV gamma
/score/quantity/flatSurfaceFlux fux434 
/score/filter/particleWithKineticEnergy range434 4344.0 4354.0 keV gamma
/score/quantity/flatSurfaceFlux fux435 
/score/filter/particleWithKineticEnergy range435 4354.0 4364.0 keV gamma
/score/quantity/flatSurfaceFlux fux436 
/score/filter/particleWithKineticEnergy range436 4364.0 4374.0 keV gamma
/score/quantity/flatSurfaceFlux fux437 
/score/filter/particleWithKineticEnergy range437 4374.0 4384.0 keV gamma
/score/quantity/flatSurfaceFlux fux438 
/score/filter/particleWithKineticEnergy range438 4384.0 4394.0 keV gamma
/score/quantity/flatSurfaceFlux fux439 
/score/filter/particleWithKineticEnergy range439 4394.0 4404.0 keV gamma
/score/quantity/flatSurfaceFlux fux440 
/score/filter/particleWithKineticEnergy range440 4404.0 4414.0 keV gamma
/score/quantity/flatSurfaceFlux fux441 
/score/filter/particleWithKineticEnergy range441 4414.0 4424.0 keV gamma
/score/quantity/flatSurfaceFlux fux442 
/score/filter/particleWithKineticEnergy range442 4424.0 4434.0 keV gamma
/score/quantity/flatSurfaceFlux fux443 
/score/filter/particleWithKineticEnergy range443 4434.0 4444.0 keV gamma
/score/quantity/flatSurfaceFlux fux444 
/score/filter/particleWithKineticEnergy range444 4444.0 4454.0 keV gamma
/score/quantity/flatSurfaceFlux fux445 
/score/filter/particleWithKineticEnergy range445 4454.0 4464.0 keV gamma
/score/quantity/flatSurfaceFlux fux446 
/score/filter/particleWithKineticEnergy range446 4464.0 4474.0 keV gamma
/score/quantity/flatSurfaceFlux fux447 
/score/filter/particleWithKineticEnergy range447 4474.0 4484.0 keV gamma
/score/quantity/flatSurfaceFlux fux448 
/score/filter/particleWithKineticEnergy range448 4484.0 4494.0 keV gamma
/score/quantity/flatSurfaceFlux fux449 
/score/filter/particleWithKineticEnergy range449 4494.0 4505.0 keV gamma
/score/quantity/flatSurfaceFlux fux450 
/score/filter/particleWithKineticEnergy range450 4505.0 4515.0 keV gamma
/score/quantity/flatSurfaceFlux fux451 
/score/filter/particleWithKineticEnergy range451 4515.0 4525.0 keV gamma
/score/quantity/flatSurfaceFlux fux452 
/score/filter/particleWithKineticEnergy range452 4525.0 4535.0 keV gamma
/score/quantity/flatSurfaceFlux fux453 
/score/filter/particleWithKineticEnergy range453 4535.0 4545.0 keV gamma
/score/quantity/flatSurfaceFlux fux454 
/score/filter/particleWithKineticEnergy range454 4545.0 4555.0 keV gamma
/score/quantity/flatSurfaceFlux fux455 
/score/filter/particleWithKineticEnergy range455 4555.0 4565.0 keV gamma
/score/quantity/flatSurfaceFlux fux456 
/score/filter/particleWithKineticEnergy range456 4565.0 4575.0 keV gamma
/score/quantity/flatSurfaceFlux fux457 
/score/filter/particleWithKineticEnergy range457 4575.0 4585.0 keV gamma
/score/quantity/flatSurfaceFlux fux458 
/score/filter/particleWithKineticEnergy range458 4585.0 4595.0 keV gamma
/score/quantity/flatSurfaceFlux fux459 
/score/filter/particleWithKineticEnergy range459 4595.0 4605.0 keV gamma
/score/quantity/flatSurfaceFlux fux460 
/score/filter/particleWithKineticEnergy range460 4605.0 4615.0 keV gamma
/score/quantity/flatSurfaceFlux fux461 
/score/filter/particleWithKineticEnergy range461 4615.0 4625.0 keV gamma
/score/quantity/flatSurfaceFlux fux462 
/score/filter/particleWithKineticEnergy range462 4625.0 4635.0 keV gamma
/score/quantity/flatSurfaceFlux fux463 
/score/filter/particleWithKineticEnergy range463 4635.0 4645.0 keV gamma
/score/quantity/flatSurfaceFlux fux464 
/score/filter/particleWithKineticEnergy range464 4645.0 4655.0 keV gamma
/score/quantity/flatSurfaceFlux fux465 
/score/filter/particleWithKineticEnergy range465 4655.0 4665.0 keV gamma
/score/quantity/flatSurfaceFlux fux466 
/score/filter/particleWithKineticEnergy range466 4665.0 4675.0 keV gamma
/score/quantity/flatSurfaceFlux fux467 
/score/filter/particleWithKineticEnergy range467 4675.0 4685.0 keV gamma
/score/quantity/flatSurfaceFlux fux468 
/score/filter/particleWithKineticEnergy range468 4685.0 4695.0 keV gamma
/score/quantity/flatSurfaceFlux fux469 
/score/filter/particleWithKineticEnergy range469 4695.0 4705.0 keV gamma
/score/quantity/flatSurfaceFlux fux470 
/score/filter/particleWithKineticEnergy range470 4705.0 4715.0 keV gamma
/score/quantity/flatSurfaceFlux fux471 
/score/filter/particleWithKineticEnergy range471 4715.0 4725.0 keV gamma
/score/quantity/flatSurfaceFlux fux472 
/score/filter/particleWithKineticEnergy range472 4725.0 4735.0 keV gamma
/score/quantity/flatSurfaceFlux fux473 
/score/filter/particleWithKineticEnergy range473 4735.0 4745.0 keV gamma
/score/quantity/flatSurfaceFlux fux474 
/score/filter/particleWithKineticEnergy range474 4745.0 4755.0 keV gamma
/score/quantity/flatSurfaceFlux fux475 
/score/filter/particleWithKineticEnergy range475 4755.0 4765.0 keV gamma
/score/quantity/flatSurfaceFlux fux476 
/score/filter/particleWithKineticEnergy range476 4765.0 4775.0 keV gamma
/score/quantity/flatSurfaceFlux fux477 
/score/filter/particleWithKineticEnergy range477 4775.0 4785.0 keV gamma
/score/quantity/flatSurfaceFlux fux478 
/score/filter/particleWithKineticEnergy range478 4785.0 4795.0 keV gamma
/score/quantity/flatSurfaceFlux fux479 
/score/filter/particleWithKineticEnergy range479 4795.0 4805.0 keV gamma
/score/quantity/flatSurfaceFlux fux480 
/score/filter/particleWithKineticEnergy range480 4805.0 4815.0 keV gamma
/score/quantity/flatSurfaceFlux fux481 
/score/filter/particleWithKineticEnergy range481 4815.0 4825.0 keV gamma
/score/quantity/flatSurfaceFlux fux482 
/score/filter/particleWithKineticEnergy range482 4825.0 4835.0 keV gamma
/score/quantity/flatSurfaceFlux fux483 
/score/filter/particleWithKineticEnergy range483 4835.0 4845.0 keV gamma
/score/quantity/flatSurfaceFlux fux484 
/score/filter/particleWithKineticEnergy range484 4845.0 4855.0 keV gamma
/score/quantity/flatSurfaceFlux fux485 
/score/filter/particleWithKineticEnergy range485 4855.0 4865.0 keV gamma
/score/quantity/flatSurfaceFlux fux486 
/score/filter/particleWithKineticEnergy range486 4865.0 4875.0 keV gamma
/score/quantity/flatSurfaceFlux fux487 
/score/filter/particleWithKineticEnergy range487 4875.0 4885.0 keV gamma
/score/quantity/flatSurfaceFlux fux488 
/score/filter/particleWithKineticEnergy range488 4885.0 4895.0 keV gamma
/score/quantity/flatSurfaceFlux fux489 
/score/filter/particleWithKineticEnergy range489 4895.0 4905.0 keV gamma
/score/quantity/flatSurfaceFlux fux490 
/score/filter/particleWithKineticEnergy range490 4905.0 4915.0 keV gamma
/score/quantity/flatSurfaceFlux fux491 
/score/filter/particleWithKineticEnergy range491 4915.0 4925.0 keV gamma
/score/quantity/flatSurfaceFlux fux492 
/score/filter/particleWithKineticEnergy range492 4925.0 4935.0 keV gamma
/score/quantity/flatSurfaceFlux fux493 
/score/filter/particleWithKineticEnergy range493 4935.0 4945.0 keV gamma
/score/quantity/flatSurfaceFlux fux494 
/score/filter/particleWithKineticEnergy range494 4945.0 4955.0 keV gamma
/score/quantity/flatSurfaceFlux fux495 
/score/filter/particleWithKineticEnergy range495 4955.0 4965.0 keV gamma
/score/quantity/flatSurfaceFlux fux496 
/score/filter/particleWithKineticEnergy range496 4965.0 4975.0 keV gamma
/score/quantity/flatSurfaceFlux fux497 
/score/filter/particleWithKineticEnergy range497 4975.0 4985.0 keV gamma
/score/quantity/flatSurfaceFlux fux498 
/score/filter/particleWithKineticEnergy range498 4985.0 4995.0 keV gamma
/score/quantity/flatSurfaceFlux fux499 
/score/filter/particleWithKineticEnergy range499 4995.0 5005.0 keV gamma
/score/quantity/flatSurfaceFlux fux500 
/score/filter/particleWithKineticEnergy range500 5005.0 5015.0 keV gamma
/score/quantity/flatSurfaceFlux fux501 
/score/filter/particleWithKineticEnergy range501 5015.0 5025.0 keV gamma
/score/quantity/flatSurfaceFlux fux502 
/score/filter/particleWithKineticEnergy range502 5025.0 5035.0 keV gamma
/score/quantity/flatSurfaceFlux fux503 
/score/filter/particleWithKineticEnergy range503 5035.0 5045.0 keV gamma
/score/quantity/flatSurfaceFlux fux504 
/score/filter/particleWithKineticEnergy range504 5045.0 5055.0 keV gamma
/score/quantity/flatSurfaceFlux fux505 
/score/filter/particleWithKineticEnergy range505 5055.0 5065.0 keV gamma
/score/quantity/flatSurfaceFlux fux506 
/score/filter/particleWithKineticEnergy range506 5065.0 5075.0 keV gamma
/score/quantity/flatSurfaceFlux fux507 
/score/filter/particleWithKineticEnergy range507 5075.0 5085.0 keV gamma
/score/quantity/flatSurfaceFlux fux508 
/score/filter/particleWithKineticEnergy range508 5085.0 5095.0 keV gamma
/score/quantity/flatSurfaceFlux fux509 
/score/filter/particleWithKineticEnergy range509 5095.0 5105.0 keV gamma
/score/quantity/flatSurfaceFlux fux510 
/score/filter/particleWithKineticEnergy range510 5105.0 5115.0 keV gamma
/score/quantity/flatSurfaceFlux fux511 
/score/filter/particleWithKineticEnergy range511 5115.0 5125.0 keV gamma
/score/quantity/flatSurfaceFlux fux512 
/score/filter/particleWithKineticEnergy range512 5125.0 5135.0 keV gamma
/score/quantity/flatSurfaceFlux fux513 
/score/filter/particleWithKineticEnergy range513 5135.0 5145.0 keV gamma
/score/quantity/flatSurfaceFlux fux514 
/score/filter/particleWithKineticEnergy range514 5145.0 5155.0 keV gamma
/score/quantity/flatSurfaceFlux fux515 
/score/filter/particleWithKineticEnergy range515 5155.0 5165.0 keV gamma
/score/quantity/flatSurfaceFlux fux516 
/score/filter/particleWithKineticEnergy range516 5165.0 5175.0 keV gamma
/score/quantity/flatSurfaceFlux fux517 
/score/filter/particleWithKineticEnergy range517 5175.0 5185.0 keV gamma
/score/quantity/flatSurfaceFlux fux518 
/score/filter/particleWithKineticEnergy range518 5185.0 5195.0 keV gamma
/score/quantity/flatSurfaceFlux fux519 
/score/filter/particleWithKineticEnergy range519 5195.0 5205.0 keV gamma
/score/quantity/flatSurfaceFlux fux520 
/score/filter/particleWithKineticEnergy range520 5205.0 5215.0 keV gamma
/score/quantity/flatSurfaceFlux fux521 
/score/filter/particleWithKineticEnergy range521 5215.0 5225.0 keV gamma
/score/quantity/flatSurfaceFlux fux522 
/score/filter/particleWithKineticEnergy range522 5225.0 5235.0 keV gamma
/score/quantity/flatSurfaceFlux fux523 
/score/filter/particleWithKineticEnergy range523 5235.0 5245.0 keV gamma
/score/quantity/flatSurfaceFlux fux524 
/score/filter/particleWithKineticEnergy range524 5245.0 5255.0 keV gamma
/score/quantity/flatSurfaceFlux fux525 
/score/filter/particleWithKineticEnergy range525 5255.0 5265.0 keV gamma
/score/quantity/flatSurfaceFlux fux526 
/score/filter/particleWithKineticEnergy range526 5265.0 5275.0 keV gamma
/score/quantity/flatSurfaceFlux fux527 
/score/filter/particleWithKineticEnergy range527 5275.0 5285.0 keV gamma
/score/quantity/flatSurfaceFlux fux528 
/score/filter/particleWithKineticEnergy range528 5285.0 5295.0 keV gamma
/score/quantity/flatSurfaceFlux fux529 
/score/filter/particleWithKineticEnergy range529 5295.0 5305.0 keV gamma
/score/quantity/flatSurfaceFlux fux530 
/score/filter/particleWithKineticEnergy range530 5305.0 5315.0 keV gamma
/score/quantity/flatSurfaceFlux fux531 
/score/filter/particleWithKineticEnergy range531 5315.0 5325.0 keV gamma
/score/quantity/flatSurfaceFlux fux532 
/score/filter/particleWithKineticEnergy range532 5325.0 5335.0 keV gamma
/score/quantity/flatSurfaceFlux fux533 
/score/filter/particleWithKineticEnergy range533 5335.0 5345.0 keV gamma
/score/quantity/flatSurfaceFlux fux534 
/score/filter/particleWithKineticEnergy range534 5345.0 5355.0 keV gamma
/score/quantity/flatSurfaceFlux fux535 
/score/filter/particleWithKineticEnergy range535 5355.0 5365.0 keV gamma
/score/quantity/flatSurfaceFlux fux536 
/score/filter/particleWithKineticEnergy range536 5365.0 5375.0 keV gamma
/score/quantity/flatSurfaceFlux fux537 
/score/filter/particleWithKineticEnergy range537 5375.0 5385.0 keV gamma
/score/quantity/flatSurfaceFlux fux538 
/score/filter/particleWithKineticEnergy range538 5385.0 5395.0 keV gamma
/score/quantity/flatSurfaceFlux fux539 
/score/filter/particleWithKineticEnergy range539 5395.0 5405.0 keV gamma
/score/quantity/flatSurfaceFlux fux540 
/score/filter/particleWithKineticEnergy range540 5405.0 5415.0 keV gamma
/score/quantity/flatSurfaceFlux fux541 
/score/filter/particleWithKineticEnergy range541 5415.0 5425.0 keV gamma
/score/quantity/flatSurfaceFlux fux542 
/score/filter/particleWithKineticEnergy range542 5425.0 5435.0 keV gamma
/score/quantity/flatSurfaceFlux fux543 
/score/filter/particleWithKineticEnergy range543 5435.0 5445.0 keV gamma
/score/quantity/flatSurfaceFlux fux544 
/score/filter/particleWithKineticEnergy range544 5445.0 5455.0 keV gamma
/score/quantity/flatSurfaceFlux fux545 
/score/filter/particleWithKineticEnergy range545 5455.0 5465.0 keV gamma
/score/quantity/flatSurfaceFlux fux546 
/score/filter/particleWithKineticEnergy range546 5465.0 5475.0 keV gamma
/score/quantity/flatSurfaceFlux fux547 
/score/filter/particleWithKineticEnergy range547 5475.0 5485.0 keV gamma
/score/quantity/flatSurfaceFlux fux548 
/score/filter/particleWithKineticEnergy range548 5485.0 5495.0 keV gamma
/score/quantity/flatSurfaceFlux fux549 
/score/filter/particleWithKineticEnergy range549 5495.0 5506.0 keV gamma
/score/quantity/flatSurfaceFlux fux550 
/score/filter/particleWithKineticEnergy range550 5506.0 5516.0 keV gamma
/score/quantity/flatSurfaceFlux fux551 
/score/filter/particleWithKineticEnergy range551 5516.0 5526.0 keV gamma
/score/quantity/flatSurfaceFlux fux552 
/score/filter/particleWithKineticEnergy range552 5526.0 5536.0 keV gamma
/score/quantity/flatSurfaceFlux fux553 
/score/filter/particleWithKineticEnergy range553 5536.0 5546.0 keV gamma
/score/quantity/flatSurfaceFlux fux554 
/score/filter/particleWithKineticEnergy range554 5546.0 5556.0 keV gamma
/score/quantity/flatSurfaceFlux fux555 
/score/filter/particleWithKineticEnergy range555 5556.0 5566.0 keV gamma
/score/quantity/flatSurfaceFlux fux556 
/score/filter/particleWithKineticEnergy range556 5566.0 5576.0 keV gamma
/score/quantity/flatSurfaceFlux fux557 
/score/filter/particleWithKineticEnergy range557 5576.0 5586.0 keV gamma
/score/quantity/flatSurfaceFlux fux558 
/score/filter/particleWithKineticEnergy range558 5586.0 5596.0 keV gamma
/score/quantity/flatSurfaceFlux fux559 
/score/filter/particleWithKineticEnergy range559 5596.0 5606.0 keV gamma
/score/quantity/flatSurfaceFlux fux560 
/score/filter/particleWithKineticEnergy range560 5606.0 5616.0 keV gamma
/score/quantity/flatSurfaceFlux fux561 
/score/filter/particleWithKineticEnergy range561 5616.0 5626.0 keV gamma
/score/quantity/flatSurfaceFlux fux562 
/score/filter/particleWithKineticEnergy range562 5626.0 5636.0 keV gamma
/score/quantity/flatSurfaceFlux fux563 
/score/filter/particleWithKineticEnergy range563 5636.0 5646.0 keV gamma
/score/quantity/flatSurfaceFlux fux564 
/score/filter/particleWithKineticEnergy range564 5646.0 5656.0 keV gamma
/score/quantity/flatSurfaceFlux fux565 
/score/filter/particleWithKineticEnergy range565 5656.0 5666.0 keV gamma
/score/quantity/flatSurfaceFlux fux566 
/score/filter/particleWithKineticEnergy range566 5666.0 5676.0 keV gamma
/score/quantity/flatSurfaceFlux fux567 
/score/filter/particleWithKineticEnergy range567 5676.0 5686.0 keV gamma
/score/quantity/flatSurfaceFlux fux568 
/score/filter/particleWithKineticEnergy range568 5686.0 5696.0 keV gamma
/score/quantity/flatSurfaceFlux fux569 
/score/filter/particleWithKineticEnergy range569 5696.0 5706.0 keV gamma
/score/quantity/flatSurfaceFlux fux570 
/score/filter/particleWithKineticEnergy range570 5706.0 5716.0 keV gamma
/score/quantity/flatSurfaceFlux fux571 
/score/filter/particleWithKineticEnergy range571 5716.0 5726.0 keV gamma
/score/quantity/flatSurfaceFlux fux572 
/score/filter/particleWithKineticEnergy range572 5726.0 5736.0 keV gamma
/score/quantity/flatSurfaceFlux fux573 
/score/filter/particleWithKineticEnergy range573 5736.0 5746.0 keV gamma
/score/quantity/flatSurfaceFlux fux574 
/score/filter/particleWithKineticEnergy range574 5746.0 5756.0 keV gamma
/score/quantity/flatSurfaceFlux fux575 
/score/filter/particleWithKineticEnergy range575 5756.0 5766.0 keV gamma
/score/quantity/flatSurfaceFlux fux576 
/score/filter/particleWithKineticEnergy range576 5766.0 5776.0 keV gamma
/score/quantity/flatSurfaceFlux fux577 
/score/filter/particleWithKineticEnergy range577 5776.0 5786.0 keV gamma
/score/quantity/flatSurfaceFlux fux578 
/score/filter/particleWithKineticEnergy range578 5786.0 5796.0 keV gamma
/score/quantity/flatSurfaceFlux fux579 
/score/filter/particleWithKineticEnergy range579 5796.0 5806.0 keV gamma
/score/quantity/flatSurfaceFlux fux580 
/score/filter/particleWithKineticEnergy range580 5806.0 5816.0 keV gamma
/score/quantity/flatSurfaceFlux fux581 
/score/filter/particleWithKineticEnergy range581 5816.0 5826.0 keV gamma
/score/quantity/flatSurfaceFlux fux582 
/score/filter/particleWithKineticEnergy range582 5826.0 5836.0 keV gamma
/score/quantity/flatSurfaceFlux fux583 
/score/filter/particleWithKineticEnergy range583 5836.0 5846.0 keV gamma
/score/quantity/flatSurfaceFlux fux584 
/score/filter/particleWithKineticEnergy range584 5846.0 5856.0 keV gamma
/score/quantity/flatSurfaceFlux fux585 
/score/filter/particleWithKineticEnergy range585 5856.0 5866.0 keV gamma
/score/quantity/flatSurfaceFlux fux586 
/score/filter/particleWithKineticEnergy range586 5866.0 5876.0 keV gamma
/score/quantity/flatSurfaceFlux fux587 
/score/filter/particleWithKineticEnergy range587 5876.0 5886.0 keV gamma
/score/quantity/flatSurfaceFlux fux588 
/score/filter/particleWithKineticEnergy range588 5886.0 5896.0 keV gamma
/score/quantity/flatSurfaceFlux fux589 
/score/filter/particleWithKineticEnergy range589 5896.0 5906.0 keV gamma
/score/quantity/flatSurfaceFlux fux590 
/score/filter/particleWithKineticEnergy range590 5906.0 5916.0 keV gamma
/score/quantity/flatSurfaceFlux fux591 
/score/filter/particleWithKineticEnergy range591 5916.0 5926.0 keV gamma
/score/quantity/flatSurfaceFlux fux592 
/score/filter/particleWithKineticEnergy range592 5926.0 5936.0 keV gamma
/score/quantity/flatSurfaceFlux fux593 
/score/filter/particleWithKineticEnergy range593 5936.0 5946.0 keV gamma
/score/quantity/flatSurfaceFlux fux594 
/score/filter/particleWithKineticEnergy range594 5946.0 5956.0 keV gamma
/score/quantity/flatSurfaceFlux fux595 
/score/filter/particleWithKineticEnergy range595 5956.0 5966.0 keV gamma
/score/quantity/flatSurfaceFlux fux596 
/score/filter/particleWithKineticEnergy range596 5966.0 5976.0 keV gamma
/score/quantity/flatSurfaceFlux fux597 
/score/filter/particleWithKineticEnergy range597 5976.0 5986.0 keV gamma
/score/quantity/flatSurfaceFlux fux598 
/score/filter/particleWithKineticEnergy range598 5986.0 5996.0 keV gamma
/score/quantity/flatSurfaceFlux fux599 
/score/filter/particleWithKineticEnergy range599 5996.0 6006.0 keV gamma
/score/quantity/flatSurfaceFlux fux600 
/score/filter/particleWithKineticEnergy range600 6006.0 6016.0 keV gamma
/score/quantity/flatSurfaceFlux fux601 
/score/filter/particleWithKineticEnergy range601 6016.0 6026.0 keV gamma
/score/quantity/flatSurfaceFlux fux602 
/score/filter/particleWithKineticEnergy range602 6026.0 6036.0 keV gamma
/score/quantity/flatSurfaceFlux fux603 
/score/filter/particleWithKineticEnergy range603 6036.0 6046.0 keV gamma
/score/quantity/flatSurfaceFlux fux604 
/score/filter/particleWithKineticEnergy range604 6046.0 6056.0 keV gamma
/score/quantity/flatSurfaceFlux fux605 
/score/filter/particleWithKineticEnergy range605 6056.0 6066.0 keV gamma
/score/quantity/flatSurfaceFlux fux606 
/score/filter/particleWithKineticEnergy range606 6066.0 6076.0 keV gamma
/score/quantity/flatSurfaceFlux fux607 
/score/filter/particleWithKineticEnergy range607 6076.0 6086.0 keV gamma
/score/quantity/flatSurfaceFlux fux608 
/score/filter/particleWithKineticEnergy range608 6086.0 6096.0 keV gamma
/score/quantity/flatSurfaceFlux fux609 
/score/filter/particleWithKineticEnergy range609 6096.0 6106.0 keV gamma
/score/quantity/flatSurfaceFlux fux610 
/score/filter/particleWithKineticEnergy range610 6106.0 6116.0 keV gamma
/score/quantity/flatSurfaceFlux fux611 
/score/filter/particleWithKineticEnergy range611 6116.0 6126.0 keV gamma
/score/quantity/flatSurfaceFlux fux612 
/score/filter/particleWithKineticEnergy range612 6126.0 6136.0 keV gamma
/score/quantity/flatSurfaceFlux fux613 
/score/filter/particleWithKineticEnergy range613 6136.0 6146.0 keV gamma
/score/quantity/flatSurfaceFlux fux614 
/score/filter/particleWithKineticEnergy range614 6146.0 6156.0 keV gamma
/score/quantity/flatSurfaceFlux fux615 
/score/filter/particleWithKineticEnergy range615 6156.0 6166.0 keV gamma
/score/quantity/flatSurfaceFlux fux616 
/score/filter/particleWithKineticEnergy range616 6166.0 6176.0 keV gamma
/score/quantity/flatSurfaceFlux fux617 
/score/filter/particleWithKineticEnergy range617 6176.0 6186.0 keV gamma
/score/quantity/flatSurfaceFlux fux618 
/score/filter/particleWithKineticEnergy range618 6186.0 6196.0 keV gamma
/score/quantity/flatSurfaceFlux fux619 
/score/filter/particleWithKineticEnergy range619 6196.0 6206.0 keV gamma
/score/quantity/flatSurfaceFlux fux620 
/score/filter/particleWithKineticEnergy range620 6206.0 6216.0 keV gamma
/score/quantity/flatSurfaceFlux fux621 
/score/filter/particleWithKineticEnergy range621 6216.0 6226.0 keV gamma
/score/quantity/flatSurfaceFlux fux622 
/score/filter/particleWithKineticEnergy range622 6226.0 6236.0 keV gamma
/score/quantity/flatSurfaceFlux fux623 
/score/filter/particleWithKineticEnergy range623 6236.0 6246.0 keV gamma
/score/quantity/flatSurfaceFlux fux624 
/score/filter/particleWithKineticEnergy range624 6246.0 6256.0 keV gamma
/score/quantity/flatSurfaceFlux fux625 
/score/filter/particleWithKineticEnergy range625 6256.0 6266.0 keV gamma
/score/quantity/flatSurfaceFlux fux626 
/score/filter/particleWithKineticEnergy range626 6266.0 6276.0 keV gamma
/score/quantity/flatSurfaceFlux fux627 
/score/filter/particleWithKineticEnergy range627 6276.0 6286.0 keV gamma
/score/quantity/flatSurfaceFlux fux628 
/score/filter/particleWithKineticEnergy range628 6286.0 6296.0 keV gamma
/score/quantity/flatSurfaceFlux fux629 
/score/filter/particleWithKineticEnergy range629 6296.0 6306.0 keV gamma
/score/quantity/flatSurfaceFlux fux630 
/score/filter/particleWithKineticEnergy range630 6306.0 6316.0 keV gamma
/score/quantity/flatSurfaceFlux fux631 
/score/filter/particleWithKineticEnergy range631 6316.0 6326.0 keV gamma
/score/quantity/flatSurfaceFlux fux632 
/score/filter/particleWithKineticEnergy range632 6326.0 6336.0 keV gamma
/score/quantity/flatSurfaceFlux fux633 
/score/filter/particleWithKineticEnergy range633 6336.0 6346.0 keV gamma
/score/quantity/flatSurfaceFlux fux634 
/score/filter/particleWithKineticEnergy range634 6346.0 6356.0 keV gamma
/score/quantity/flatSurfaceFlux fux635 
/score/filter/particleWithKineticEnergy range635 6356.0 6366.0 keV gamma
/score/quantity/flatSurfaceFlux fux636 
/score/filter/particleWithKineticEnergy range636 6366.0 6376.0 keV gamma
/score/quantity/flatSurfaceFlux fux637 
/score/filter/particleWithKineticEnergy range637 6376.0 6386.0 keV gamma
/score/quantity/flatSurfaceFlux fux638 
/score/filter/particleWithKineticEnergy range638 6386.0 6396.0 keV gamma
/score/quantity/flatSurfaceFlux fux639 
/score/filter/particleWithKineticEnergy range639 6396.0 6406.0 keV gamma
/score/quantity/flatSurfaceFlux fux640 
/score/filter/particleWithKineticEnergy range640 6406.0 6416.0 keV gamma
/score/quantity/flatSurfaceFlux fux641 
/score/filter/particleWithKineticEnergy range641 6416.0 6426.0 keV gamma
/score/quantity/flatSurfaceFlux fux642 
/score/filter/particleWithKineticEnergy range642 6426.0 6436.0 keV gamma
/score/quantity/flatSurfaceFlux fux643 
/score/filter/particleWithKineticEnergy range643 6436.0 6446.0 keV gamma
/score/quantity/flatSurfaceFlux fux644 
/score/filter/particleWithKineticEnergy range644 6446.0 6456.0 keV gamma
/score/quantity/flatSurfaceFlux fux645 
/score/filter/particleWithKineticEnergy range645 6456.0 6466.0 keV gamma
/score/quantity/flatSurfaceFlux fux646 
/score/filter/particleWithKineticEnergy range646 6466.0 6476.0 keV gamma
/score/quantity/flatSurfaceFlux fux647 
/score/filter/particleWithKineticEnergy range647 6476.0 6486.0 keV gamma
/score/quantity/flatSurfaceFlux fux648 
/score/filter/particleWithKineticEnergy range648 6486.0 6496.0 keV gamma
/score/quantity/flatSurfaceFlux fux649 
/score/filter/particleWithKineticEnergy range649 6496.0 6507.0 keV gamma
/score/quantity/flatSurfaceFlux fux650 
/score/filter/particleWithKineticEnergy range650 6507.0 6517.0 keV gamma
/score/quantity/flatSurfaceFlux fux651 
/score/filter/particleWithKineticEnergy range651 6517.0 6527.0 keV gamma
/score/quantity/flatSurfaceFlux fux652 
/score/filter/particleWithKineticEnergy range652 6527.0 6537.0 keV gamma
/score/quantity/flatSurfaceFlux fux653 
/score/filter/particleWithKineticEnergy range653 6537.0 6547.0 keV gamma
/score/quantity/flatSurfaceFlux fux654 
/score/filter/particleWithKineticEnergy range654 6547.0 6557.0 keV gamma
/score/quantity/flatSurfaceFlux fux655 
/score/filter/particleWithKineticEnergy range655 6557.0 6567.0 keV gamma
/score/quantity/flatSurfaceFlux fux656 
/score/filter/particleWithKineticEnergy range656 6567.0 6577.0 keV gamma
/score/quantity/flatSurfaceFlux fux657 
/score/filter/particleWithKineticEnergy range657 6577.0 6587.0 keV gamma
/score/quantity/flatSurfaceFlux fux658 
/score/filter/particleWithKineticEnergy range658 6587.0 6597.0 keV gamma
/score/quantity/flatSurfaceFlux fux659 
/score/filter/particleWithKineticEnergy range659 6597.0 6607.0 keV gamma
/score/quantity/flatSurfaceFlux fux660 
/score/filter/particleWithKineticEnergy range660 6607.0 6617.0 keV gamma
/score/quantity/flatSurfaceFlux fux661 
/score/filter/particleWithKineticEnergy range661 6617.0 6627.0 keV gamma
/score/quantity/flatSurfaceFlux fux662 
/score/filter/particleWithKineticEnergy range662 6627.0 6637.0 keV gamma
/score/quantity/flatSurfaceFlux fux663 
/score/filter/particleWithKineticEnergy range663 6637.0 6647.0 keV gamma
/score/quantity/flatSurfaceFlux fux664 
/score/filter/particleWithKineticEnergy range664 6647.0 6657.0 keV gamma
/score/quantity/flatSurfaceFlux fux665 
/score/filter/particleWithKineticEnergy range665 6657.0 6667.0 keV gamma
/score/quantity/flatSurfaceFlux fux666 
/score/filter/particleWithKineticEnergy range666 6667.0 6677.0 keV gamma
/score/quantity/flatSurfaceFlux fux667 
/score/filter/particleWithKineticEnergy range667 6677.0 6687.0 keV gamma
/score/quantity/flatSurfaceFlux fux668 
/score/filter/particleWithKineticEnergy range668 6687.0 6697.0 keV gamma
/score/quantity/flatSurfaceFlux fux669 
/score/filter/particleWithKineticEnergy range669 6697.0 6707.0 keV gamma
/score/quantity/flatSurfaceFlux fux670 
/score/filter/particleWithKineticEnergy range670 6707.0 6717.0 keV gamma
/score/quantity/flatSurfaceFlux fux671 
/score/filter/particleWithKineticEnergy range671 6717.0 6727.0 keV gamma
/score/quantity/flatSurfaceFlux fux672 
/score/filter/particleWithKineticEnergy range672 6727.0 6737.0 keV gamma
/score/quantity/flatSurfaceFlux fux673 
/score/filter/particleWithKineticEnergy range673 6737.0 6747.0 keV gamma
/score/quantity/flatSurfaceFlux fux674 
/score/filter/particleWithKineticEnergy range674 6747.0 6757.0 keV gamma
/score/quantity/flatSurfaceFlux fux675 
/score/filter/particleWithKineticEnergy range675 6757.0 6767.0 keV gamma
/score/quantity/flatSurfaceFlux fux676 
/score/filter/particleWithKineticEnergy range676 6767.0 6777.0 keV gamma
/score/quantity/flatSurfaceFlux fux677 
/score/filter/particleWithKineticEnergy range677 6777.0 6787.0 keV gamma
/score/quantity/flatSurfaceFlux fux678 
/score/filter/particleWithKineticEnergy range678 6787.0 6797.0 keV gamma
/score/quantity/flatSurfaceFlux fux679 
/score/filter/particleWithKineticEnergy range679 6797.0 6807.0 keV gamma
/score/quantity/flatSurfaceFlux fux680 
/score/filter/particleWithKineticEnergy range680 6807.0 6817.0 keV gamma
/score/quantity/flatSurfaceFlux fux681 
/score/filter/particleWithKineticEnergy range681 6817.0 6827.0 keV gamma
/score/quantity/flatSurfaceFlux fux682 
/score/filter/particleWithKineticEnergy range682 6827.0 6837.0 keV gamma
/score/quantity/flatSurfaceFlux fux683 
/score/filter/particleWithKineticEnergy range683 6837.0 6847.0 keV gamma
/score/quantity/flatSurfaceFlux fux684 
/score/filter/particleWithKineticEnergy range684 6847.0 6857.0 keV gamma
/score/quantity/flatSurfaceFlux fux685 
/score/filter/particleWithKineticEnergy range685 6857.0 6867.0 keV gamma
/score/quantity/flatSurfaceFlux fux686 
/score/filter/particleWithKineticEnergy range686 6867.0 6877.0 keV gamma
/score/quantity/flatSurfaceFlux fux687 
/score/filter/particleWithKineticEnergy range687 6877.0 6887.0 keV gamma
/score/quantity/flatSurfaceFlux fux688 
/score/filter/particleWithKineticEnergy range688 6887.0 6897.0 keV gamma
/score/quantity/flatSurfaceFlux fux689 
/score/filter/particleWithKineticEnergy range689 6897.0 6907.0 keV gamma
/score/quantity/flatSurfaceFlux fux690 
/score/filter/particleWithKineticEnergy range690 6907.0 6917.0 keV gamma
/score/quantity/flatSurfaceFlux fux691 
/score/filter/particleWithKineticEnergy range691 6917.0 6927.0 keV gamma
/score/quantity/flatSurfaceFlux fux692 
/score/filter/particleWithKineticEnergy range692 6927.0 6937.0 keV gamma
/score/quantity/flatSurfaceFlux fux693 
/score/filter/particleWithKineticEnergy range693 6937.0 6947.0 keV gamma
/score/quantity/flatSurfaceFlux fux694 
/score/filter/particleWithKineticEnergy range694 6947.0 6957.0 keV gamma
/score/quantity/flatSurfaceFlux fux695 
/score/filter/particleWithKineticEnergy range695 6957.0 6967.0 keV gamma
/score/quantity/flatSurfaceFlux fux696 
/score/filter/particleWithKineticEnergy range696 6967.0 6977.0 keV gamma
/score/quantity/flatSurfaceFlux fux697 
/score/filter/particleWithKineticEnergy range697 6977.0 6987.0 keV gamma
/score/quantity/flatSurfaceFlux fux698 
/score/filter/particleWithKineticEnergy range698 6987.0 6997.0 keV gamma
/score/quantity/flatSurfaceFlux fux699 
/score/filter/particleWithKineticEnergy range699 6997.0 7007.0 keV gamma
/score/quantity/flatSurfaceFlux fux700 
/score/filter/particleWithKineticEnergy range700 7007.0 7017.0 keV gamma
/score/quantity/flatSurfaceFlux fux701 
/score/filter/particleWithKineticEnergy range701 7017.0 7027.0 keV gamma
/score/quantity/flatSurfaceFlux fux702 
/score/filter/particleWithKineticEnergy range702 7027.0 7037.0 keV gamma
/score/quantity/flatSurfaceFlux fux703 
/score/filter/particleWithKineticEnergy range703 7037.0 7047.0 keV gamma
/score/quantity/flatSurfaceFlux fux704 
/score/filter/particleWithKineticEnergy range704 7047.0 7057.0 keV gamma
/score/quantity/flatSurfaceFlux fux705 
/score/filter/particleWithKineticEnergy range705 7057.0 7067.0 keV gamma
/score/quantity/flatSurfaceFlux fux706 
/score/filter/particleWithKineticEnergy range706 7067.0 7077.0 keV gamma
/score/quantity/flatSurfaceFlux fux707 
/score/filter/particleWithKineticEnergy range707 7077.0 7087.0 keV gamma
/score/quantity/flatSurfaceFlux fux708 
/score/filter/particleWithKineticEnergy range708 7087.0 7097.0 keV gamma
/score/quantity/flatSurfaceFlux fux709 
/score/filter/particleWithKineticEnergy range709 7097.0 7107.0 keV gamma
/score/quantity/flatSurfaceFlux fux710 
/score/filter/particleWithKineticEnergy range710 7107.0 7117.0 keV gamma
/score/quantity/flatSurfaceFlux fux711 
/score/filter/particleWithKineticEnergy range711 7117.0 7127.0 keV gamma
/score/quantity/flatSurfaceFlux fux712 
/score/filter/particleWithKineticEnergy range712 7127.0 7137.0 keV gamma
/score/quantity/flatSurfaceFlux fux713 
/score/filter/particleWithKineticEnergy range713 7137.0 7147.0 keV gamma
/score/quantity/flatSurfaceFlux fux714 
/score/filter/particleWithKineticEnergy range714 7147.0 7157.0 keV gamma
/score/quantity/flatSurfaceFlux fux715 
/score/filter/particleWithKineticEnergy range715 7157.0 7167.0 keV gamma
/score/quantity/flatSurfaceFlux fux716 
/score/filter/particleWithKineticEnergy range716 7167.0 7177.0 keV gamma
/score/quantity/flatSurfaceFlux fux717 
/score/filter/particleWithKineticEnergy range717 7177.0 7187.0 keV gamma
/score/quantity/flatSurfaceFlux fux718 
/score/filter/particleWithKineticEnergy range718 7187.0 7197.0 keV gamma
/score/quantity/flatSurfaceFlux fux719 
/score/filter/particleWithKineticEnergy range719 7197.0 7207.0 keV gamma
/score/quantity/flatSurfaceFlux fux720 
/score/filter/particleWithKineticEnergy range720 7207.0 7217.0 keV gamma
/score/quantity/flatSurfaceFlux fux721 
/score/filter/particleWithKineticEnergy range721 7217.0 7227.0 keV gamma
/score/quantity/flatSurfaceFlux fux722 
/score/filter/particleWithKineticEnergy range722 7227.0 7237.0 keV gamma
/score/quantity/flatSurfaceFlux fux723 
/score/filter/particleWithKineticEnergy range723 7237.0 7247.0 keV gamma
/score/quantity/flatSurfaceFlux fux724 
/score/filter/particleWithKineticEnergy range724 7247.0 7257.0 keV gamma
/score/quantity/flatSurfaceFlux fux725 
/score/filter/particleWithKineticEnergy range725 7257.0 7267.0 keV gamma
/score/quantity/flatSurfaceFlux fux726 
/score/filter/particleWithKineticEnergy range726 7267.0 7277.0 keV gamma
/score/quantity/flatSurfaceFlux fux727 
/score/filter/particleWithKineticEnergy range727 7277.0 7287.0 keV gamma
/score/quantity/flatSurfaceFlux fux728 
/score/filter/particleWithKineticEnergy range728 7287.0 7297.0 keV gamma
/score/quantity/flatSurfaceFlux fux729 
/score/filter/particleWithKineticEnergy range729 7297.0 7307.0 keV gamma
/score/quantity/flatSurfaceFlux fux730 
/score/filter/particleWithKineticEnergy range730 7307.0 7317.0 keV gamma
/score/quantity/flatSurfaceFlux fux731 
/score/filter/particleWithKineticEnergy range731 7317.0 7327.0 keV gamma
/score/quantity/flatSurfaceFlux fux732 
/score/filter/particleWithKineticEnergy range732 7327.0 7337.0 keV gamma
/score/quantity/flatSurfaceFlux fux733 
/score/filter/particleWithKineticEnergy range733 7337.0 7347.0 keV gamma
/score/quantity/flatSurfaceFlux fux734 
/score/filter/particleWithKineticEnergy range734 7347.0 7357.0 keV gamma
/score/quantity/flatSurfaceFlux fux735 
/score/filter/particleWithKineticEnergy range735 7357.0 7367.0 keV gamma
/score/quantity/flatSurfaceFlux fux736 
/score/filter/particleWithKineticEnergy range736 7367.0 7377.0 keV gamma
/score/quantity/flatSurfaceFlux fux737 
/score/filter/particleWithKineticEnergy range737 7377.0 7387.0 keV gamma
/score/quantity/flatSurfaceFlux fux738 
/score/filter/particleWithKineticEnergy range738 7387.0 7397.0 keV gamma
/score/quantity/flatSurfaceFlux fux739 
/score/filter/particleWithKineticEnergy range739 7397.0 7407.0 keV gamma
/score/quantity/flatSurfaceFlux fux740 
/score/filter/particleWithKineticEnergy range740 7407.0 7417.0 keV gamma
/score/quantity/flatSurfaceFlux fux741 
/score/filter/particleWithKineticEnergy range741 7417.0 7427.0 keV gamma
/score/quantity/flatSurfaceFlux fux742 
/score/filter/particleWithKineticEnergy range742 7427.0 7437.0 keV gamma
/score/quantity/flatSurfaceFlux fux743 
/score/filter/particleWithKineticEnergy range743 7437.0 7447.0 keV gamma
/score/quantity/flatSurfaceFlux fux744 
/score/filter/particleWithKineticEnergy range744 7447.0 7457.0 keV gamma
/score/quantity/flatSurfaceFlux fux745 
/score/filter/particleWithKineticEnergy range745 7457.0 7467.0 keV gamma
/score/quantity/flatSurfaceFlux fux746 
/score/filter/particleWithKineticEnergy range746 7467.0 7477.0 keV gamma
/score/quantity/flatSurfaceFlux fux747 
/score/filter/particleWithKineticEnergy range747 7477.0 7487.0 keV gamma
/score/quantity/flatSurfaceFlux fux748 
/score/filter/particleWithKineticEnergy range748 7487.0 7497.0 keV gamma
/score/quantity/flatSurfaceFlux fux749 
/score/filter/particleWithKineticEnergy range749 7497.0 7508.0 keV gamma
/score/quantity/flatSurfaceFlux fux750 
/score/filter/particleWithKineticEnergy range750 7508.0 7518.0 keV gamma
/score/quantity/flatSurfaceFlux fux751 
/score/filter/particleWithKineticEnergy range751 7518.0 7528.0 keV gamma
/score/quantity/flatSurfaceFlux fux752 
/score/filter/particleWithKineticEnergy range752 7528.0 7538.0 keV gamma
/score/quantity/flatSurfaceFlux fux753 
/score/filter/particleWithKineticEnergy range753 7538.0 7548.0 keV gamma
/score/quantity/flatSurfaceFlux fux754 
/score/filter/particleWithKineticEnergy range754 7548.0 7558.0 keV gamma
/score/quantity/flatSurfaceFlux fux755 
/score/filter/particleWithKineticEnergy range755 7558.0 7568.0 keV gamma
/score/quantity/flatSurfaceFlux fux756 
/score/filter/particleWithKineticEnergy range756 7568.0 7578.0 keV gamma
/score/quantity/flatSurfaceFlux fux757 
/score/filter/particleWithKineticEnergy range757 7578.0 7588.0 keV gamma
/score/quantity/flatSurfaceFlux fux758 
/score/filter/particleWithKineticEnergy range758 7588.0 7598.0 keV gamma
/score/quantity/flatSurfaceFlux fux759 
/score/filter/particleWithKineticEnergy range759 7598.0 7608.0 keV gamma
/score/quantity/flatSurfaceFlux fux760 
/score/filter/particleWithKineticEnergy range760 7608.0 7618.0 keV gamma
/score/quantity/flatSurfaceFlux fux761 
/score/filter/particleWithKineticEnergy range761 7618.0 7628.0 keV gamma
/score/quantity/flatSurfaceFlux fux762 
/score/filter/particleWithKineticEnergy range762 7628.0 7638.0 keV gamma
/score/quantity/flatSurfaceFlux fux763 
/score/filter/particleWithKineticEnergy range763 7638.0 7648.0 keV gamma
/score/quantity/flatSurfaceFlux fux764 
/score/filter/particleWithKineticEnergy range764 7648.0 7658.0 keV gamma
/score/quantity/flatSurfaceFlux fux765 
/score/filter/particleWithKineticEnergy range765 7658.0 7668.0 keV gamma
/score/quantity/flatSurfaceFlux fux766 
/score/filter/particleWithKineticEnergy range766 7668.0 7678.0 keV gamma
/score/quantity/flatSurfaceFlux fux767 
/score/filter/particleWithKineticEnergy range767 7678.0 7688.0 keV gamma
/score/quantity/flatSurfaceFlux fux768 
/score/filter/particleWithKineticEnergy range768 7688.0 7698.0 keV gamma
/score/quantity/flatSurfaceFlux fux769 
/score/filter/particleWithKineticEnergy range769 7698.0 7708.0 keV gamma
/score/quantity/flatSurfaceFlux fux770 
/score/filter/particleWithKineticEnergy range770 7708.0 7718.0 keV gamma
/score/quantity/flatSurfaceFlux fux771 
/score/filter/particleWithKineticEnergy range771 7718.0 7728.0 keV gamma
/score/quantity/flatSurfaceFlux fux772 
/score/filter/particleWithKineticEnergy range772 7728.0 7738.0 keV gamma
/score/quantity/flatSurfaceFlux fux773 
/score/filter/particleWithKineticEnergy range773 7738.0 7748.0 keV gamma
/score/quantity/flatSurfaceFlux fux774 
/score/filter/particleWithKineticEnergy range774 7748.0 7758.0 keV gamma
/score/quantity/flatSurfaceFlux fux775 
/score/filter/particleWithKineticEnergy range775 7758.0 7768.0 keV gamma
/score/quantity/flatSurfaceFlux fux776 
/score/filter/particleWithKineticEnergy range776 7768.0 7778.0 keV gamma
/score/quantity/flatSurfaceFlux fux777 
/score/filter/particleWithKineticEnergy range777 7778.0 7788.0 keV gamma
/score/quantity/flatSurfaceFlux fux778 
/score/filter/particleWithKineticEnergy range778 7788.0 7798.0 keV gamma
/score/quantity/flatSurfaceFlux fux779 
/score/filter/particleWithKineticEnergy range779 7798.0 7808.0 keV gamma
/score/quantity/flatSurfaceFlux fux780 
/score/filter/particleWithKineticEnergy range780 7808.0 7818.0 keV gamma
/score/quantity/flatSurfaceFlux fux781 
/score/filter/particleWithKineticEnergy range781 7818.0 7828.0 keV gamma
/score/quantity/flatSurfaceFlux fux782 
/score/filter/particleWithKineticEnergy range782 7828.0 7838.0 keV gamma
/score/quantity/flatSurfaceFlux fux783 
/score/filter/particleWithKineticEnergy range783 7838.0 7848.0 keV gamma
/score/quantity/flatSurfaceFlux fux784 
/score/filter/particleWithKineticEnergy range784 7848.0 7858.0 keV gamma
/score/quantity/flatSurfaceFlux fux785 
/score/filter/particleWithKineticEnergy range785 7858.0 7868.0 keV gamma
/score/quantity/flatSurfaceFlux fux786 
/score/filter/particleWithKineticEnergy range786 7868.0 7878.0 keV gamma
/score/quantity/flatSurfaceFlux fux787 
/score/filter/particleWithKineticEnergy range787 7878.0 7888.0 keV gamma
/score/quantity/flatSurfaceFlux fux788 
/score/filter/particleWithKineticEnergy range788 7888.0 7898.0 keV gamma
/score/quantity/flatSurfaceFlux fux789 
/score/filter/particleWithKineticEnergy range789 7898.0 7908.0 keV gamma
/score/quantity/flatSurfaceFlux fux790 
/score/filter/particleWithKineticEnergy range790 7908.0 7918.0 keV gamma
/score/quantity/flatSurfaceFlux fux791 
/score/filter/particleWithKineticEnergy range791 7918.0 7928.0 keV gamma
/score/quantity/flatSurfaceFlux fux792 
/score/filter/particleWithKineticEnergy range792 7928.0 7938.0 keV gamma
/score/quantity/flatSurfaceFlux fux793 
/score/filter/particleWithKineticEnergy range793 7938.0 7948.0 keV gamma
/score/quantity/flatSurfaceFlux fux794 
/score/filter/particleWithKineticEnergy range794 7948.0 7958.0 keV gamma
/score/quantity/flatSurfaceFlux fux795 
/score/filter/particleWithKineticEnergy range795 7958.0 7968.0 keV gamma
/score/quantity/flatSurfaceFlux fux796 
/score/filter/particleWithKineticEnergy range796 7968.0 7978.0 keV gamma
/score/quantity/flatSurfaceFlux fux797 
/score/filter/particleWithKineticEnergy range797 7978.0 7988.0 keV gamma
/score/quantity/flatSurfaceFlux fux798 
/score/filter/particleWithKineticEnergy range798 7988.0 7998.0 keV gamma
/score/quantity/flatSurfaceFlux fux799 
/score/filter/particleWithKineticEnergy range799 7998.0 8008.0 keV gamma
/score/quantity/flatSurfaceFlux fux800 
/score/filter/particleWithKineticEnergy range800 8008.0 8018.0 keV gamma
/score/quantity/flatSurfaceFlux fux801 
/score/filter/particleWithKineticEnergy range801 8018.0 8028.0 keV gamma
/score/quantity/flatSurfaceFlux fux802 
/score/filter/particleWithKineticEnergy range802 8028.0 8038.0 keV gamma
/score/quantity/flatSurfaceFlux fux803 
/score/filter/particleWithKineticEnergy range803 8038.0 8048.0 keV gamma
/score/quantity/flatSurfaceFlux fux804 
/score/filter/particleWithKineticEnergy range804 8048.0 8058.0 keV gamma
/score/quantity/flatSurfaceFlux fux805 
/score/filter/particleWithKineticEnergy range805 8058.0 8068.0 keV gamma
/score/quantity/flatSurfaceFlux fux806 
/score/filter/particleWithKineticEnergy range806 8068.0 8078.0 keV gamma
/score/quantity/flatSurfaceFlux fux807 
/score/filter/particleWithKineticEnergy range807 8078.0 8088.0 keV gamma
/score/quantity/flatSurfaceFlux fux808 
/score/filter/particleWithKineticEnergy range808 8088.0 8098.0 keV gamma
/score/quantity/flatSurfaceFlux fux809 
/score/filter/particleWithKineticEnergy range809 8098.0 8108.0 keV gamma
/score/quantity/flatSurfaceFlux fux810 
/score/filter/particleWithKineticEnergy range810 8108.0 8118.0 keV gamma
/score/quantity/flatSurfaceFlux fux811 
/score/filter/particleWithKineticEnergy range811 8118.0 8128.0 keV gamma
/score/quantity/flatSurfaceFlux fux812 
/score/filter/particleWithKineticEnergy range812 8128.0 8138.0 keV gamma
/score/quantity/flatSurfaceFlux fux813 
/score/filter/particleWithKineticEnergy range813 8138.0 8148.0 keV gamma
/score/quantity/flatSurfaceFlux fux814 
/score/filter/particleWithKineticEnergy range814 8148.0 8158.0 keV gamma
/score/quantity/flatSurfaceFlux fux815 
/score/filter/particleWithKineticEnergy range815 8158.0 8168.0 keV gamma
/score/quantity/flatSurfaceFlux fux816 
/score/filter/particleWithKineticEnergy range816 8168.0 8178.0 keV gamma
/score/quantity/flatSurfaceFlux fux817 
/score/filter/particleWithKineticEnergy range817 8178.0 8188.0 keV gamma
/score/quantity/flatSurfaceFlux fux818 
/score/filter/particleWithKineticEnergy range818 8188.0 8198.0 keV gamma
/score/quantity/flatSurfaceFlux fux819 
/score/filter/particleWithKineticEnergy range819 8198.0 8208.0 keV gamma
/score/quantity/flatSurfaceFlux fux820 
/score/filter/particleWithKineticEnergy range820 8208.0 8218.0 keV gamma
/score/quantity/flatSurfaceFlux fux821 
/score/filter/particleWithKineticEnergy range821 8218.0 8228.0 keV gamma
/score/quantity/flatSurfaceFlux fux822 
/score/filter/particleWithKineticEnergy range822 8228.0 8238.0 keV gamma
/score/quantity/flatSurfaceFlux fux823 
/score/filter/particleWithKineticEnergy range823 8238.0 8248.0 keV gamma
/score/quantity/flatSurfaceFlux fux824 
/score/filter/particleWithKineticEnergy range824 8248.0 8258.0 keV gamma
/score/quantity/flatSurfaceFlux fux825 
/score/filter/particleWithKineticEnergy range825 8258.0 8268.0 keV gamma
/score/quantity/flatSurfaceFlux fux826 
/score/filter/particleWithKineticEnergy range826 8268.0 8278.0 keV gamma
/score/quantity/flatSurfaceFlux fux827 
/score/filter/particleWithKineticEnergy range827 8278.0 8288.0 keV gamma
/score/quantity/flatSurfaceFlux fux828 
/score/filter/particleWithKineticEnergy range828 8288.0 8298.0 keV gamma
/score/quantity/flatSurfaceFlux fux829 
/score/filter/particleWithKineticEnergy range829 8298.0 8308.0 keV gamma
/score/quantity/flatSurfaceFlux fux830 
/score/filter/particleWithKineticEnergy range830 8308.0 8318.0 keV gamma
/score/quantity/flatSurfaceFlux fux831 
/score/filter/particleWithKineticEnergy range831 8318.0 8328.0 keV gamma
/score/quantity/flatSurfaceFlux fux832 
/score/filter/particleWithKineticEnergy range832 8328.0 8338.0 keV gamma
/score/quantity/flatSurfaceFlux fux833 
/score/filter/particleWithKineticEnergy range833 8338.0 8348.0 keV gamma
/score/quantity/flatSurfaceFlux fux834 
/score/filter/particleWithKineticEnergy range834 8348.0 8358.0 keV gamma
/score/quantity/flatSurfaceFlux fux835 
/score/filter/particleWithKineticEnergy range835 8358.0 8368.0 keV gamma
/score/quantity/flatSurfaceFlux fux836 
/score/filter/particleWithKineticEnergy range836 8368.0 8378.0 keV gamma
/score/quantity/flatSurfaceFlux fux837 
/score/filter/particleWithKineticEnergy range837 8378.0 8388.0 keV gamma
/score/quantity/flatSurfaceFlux fux838 
/score/filter/particleWithKineticEnergy range838 8388.0 8398.0 keV gamma
/score/quantity/flatSurfaceFlux fux839 
/score/filter/particleWithKineticEnergy range839 8398.0 8408.0 keV gamma
/score/quantity/flatSurfaceFlux fux840 
/score/filter/particleWithKineticEnergy range840 8408.0 8418.0 keV gamma
/score/quantity/flatSurfaceFlux fux841 
/score/filter/particleWithKineticEnergy range841 8418.0 8428.0 keV gamma
/score/quantity/flatSurfaceFlux fux842 
/score/filter/particleWithKineticEnergy range842 8428.0 8438.0 keV gamma
/score/quantity/flatSurfaceFlux fux843 
/score/filter/particleWithKineticEnergy range843 8438.0 8448.0 keV gamma
/score/quantity/flatSurfaceFlux fux844 
/score/filter/particleWithKineticEnergy range844 8448.0 8458.0 keV gamma
/score/quantity/flatSurfaceFlux fux845 
/score/filter/particleWithKineticEnergy range845 8458.0 8468.0 keV gamma
/score/quantity/flatSurfaceFlux fux846 
/score/filter/particleWithKineticEnergy range846 8468.0 8478.0 keV gamma
/score/quantity/flatSurfaceFlux fux847 
/score/filter/particleWithKineticEnergy range847 8478.0 8488.0 keV gamma
/score/quantity/flatSurfaceFlux fux848 
/score/filter/particleWithKineticEnergy range848 8488.0 8498.0 keV gamma
/score/quantity/flatSurfaceFlux fux849 
/score/filter/particleWithKineticEnergy range849 8498.0 8509.0 keV gamma
/score/quantity/flatSurfaceFlux fux850 
/score/filter/particleWithKineticEnergy range850 8509.0 8519.0 keV gamma
/score/quantity/flatSurfaceFlux fux851 
/score/filter/particleWithKineticEnergy range851 8519.0 8529.0 keV gamma
/score/quantity/flatSurfaceFlux fux852 
/score/filter/particleWithKineticEnergy range852 8529.0 8539.0 keV gamma
/score/quantity/flatSurfaceFlux fux853 
/score/filter/particleWithKineticEnergy range853 8539.0 8549.0 keV gamma
/score/quantity/flatSurfaceFlux fux854 
/score/filter/particleWithKineticEnergy range854 8549.0 8559.0 keV gamma
/score/quantity/flatSurfaceFlux fux855 
/score/filter/particleWithKineticEnergy range855 8559.0 8569.0 keV gamma
/score/quantity/flatSurfaceFlux fux856 
/score/filter/particleWithKineticEnergy range856 8569.0 8579.0 keV gamma
/score/quantity/flatSurfaceFlux fux857 
/score/filter/particleWithKineticEnergy range857 8579.0 8589.0 keV gamma
/score/quantity/flatSurfaceFlux fux858 
/score/filter/particleWithKineticEnergy range858 8589.0 8599.0 keV gamma
/score/quantity/flatSurfaceFlux fux859 
/score/filter/particleWithKineticEnergy range859 8599.0 8609.0 keV gamma
/score/quantity/flatSurfaceFlux fux860 
/score/filter/particleWithKineticEnergy range860 8609.0 8619.0 keV gamma
/score/quantity/flatSurfaceFlux fux861 
/score/filter/particleWithKineticEnergy range861 8619.0 8629.0 keV gamma
/score/quantity/flatSurfaceFlux fux862 
/score/filter/particleWithKineticEnergy range862 8629.0 8639.0 keV gamma
/score/quantity/flatSurfaceFlux fux863 
/score/filter/particleWithKineticEnergy range863 8639.0 8649.0 keV gamma
/score/quantity/flatSurfaceFlux fux864 
/score/filter/particleWithKineticEnergy range864 8649.0 8659.0 keV gamma
/score/quantity/flatSurfaceFlux fux865 
/score/filter/particleWithKineticEnergy range865 8659.0 8669.0 keV gamma
/score/quantity/flatSurfaceFlux fux866 
/score/filter/particleWithKineticEnergy range866 8669.0 8679.0 keV gamma
/score/quantity/flatSurfaceFlux fux867 
/score/filter/particleWithKineticEnergy range867 8679.0 8689.0 keV gamma
/score/quantity/flatSurfaceFlux fux868 
/score/filter/particleWithKineticEnergy range868 8689.0 8699.0 keV gamma
/score/quantity/flatSurfaceFlux fux869 
/score/filter/particleWithKineticEnergy range869 8699.0 8709.0 keV gamma
/score/quantity/flatSurfaceFlux fux870 
/score/filter/particleWithKineticEnergy range870 8709.0 8719.0 keV gamma
/score/quantity/flatSurfaceFlux fux871 
/score/filter/particleWithKineticEnergy range871 8719.0 8729.0 keV gamma
/score/quantity/flatSurfaceFlux fux872 
/score/filter/particleWithKineticEnergy range872 8729.0 8739.0 keV gamma
/score/quantity/flatSurfaceFlux fux873 
/score/filter/particleWithKineticEnergy range873 8739.0 8749.0 keV gamma
/score/quantity/flatSurfaceFlux fux874 
/score/filter/particleWithKineticEnergy range874 8749.0 8759.0 keV gamma
/score/quantity/flatSurfaceFlux fux875 
/score/filter/particleWithKineticEnergy range875 8759.0 8769.0 keV gamma
/score/quantity/flatSurfaceFlux fux876 
/score/filter/particleWithKineticEnergy range876 8769.0 8779.0 keV gamma
/score/quantity/flatSurfaceFlux fux877 
/score/filter/particleWithKineticEnergy range877 8779.0 8789.0 keV gamma
/score/quantity/flatSurfaceFlux fux878 
/score/filter/particleWithKineticEnergy range878 8789.0 8799.0 keV gamma
/score/quantity/flatSurfaceFlux fux879 
/score/filter/particleWithKineticEnergy range879 8799.0 8809.0 keV gamma
/score/quantity/flatSurfaceFlux fux880 
/score/filter/particleWithKineticEnergy range880 8809.0 8819.0 keV gamma
/score/quantity/flatSurfaceFlux fux881 
/score/filter/particleWithKineticEnergy range881 8819.0 8829.0 keV gamma
/score/quantity/flatSurfaceFlux fux882 
/score/filter/particleWithKineticEnergy range882 8829.0 8839.0 keV gamma
/score/quantity/flatSurfaceFlux fux883 
/score/filter/particleWithKineticEnergy range883 8839.0 8849.0 keV gamma
/score/quantity/flatSurfaceFlux fux884 
/score/filter/particleWithKineticEnergy range884 8849.0 8859.0 keV gamma
/score/quantity/flatSurfaceFlux fux885 
/score/filter/particleWithKineticEnergy range885 8859.0 8869.0 keV gamma
/score/quantity/flatSurfaceFlux fux886 
/score/filter/particleWithKineticEnergy range886 8869.0 8879.0 keV gamma
/score/quantity/flatSurfaceFlux fux887 
/score/filter/particleWithKineticEnergy range887 8879.0 8889.0 keV gamma
/score/quantity/flatSurfaceFlux fux888 
/score/filter/particleWithKineticEnergy range888 8889.0 8899.0 keV gamma
/score/quantity/flatSurfaceFlux fux889 
/score/filter/particleWithKineticEnergy range889 8899.0 8909.0 keV gamma
/score/quantity/flatSurfaceFlux fux890 
/score/filter/particleWithKineticEnergy range890 8909.0 8919.0 keV gamma
/score/quantity/flatSurfaceFlux fux891 
/score/filter/particleWithKineticEnergy range891 8919.0 8929.0 keV gamma
/score/quantity/flatSurfaceFlux fux892 
/score/filter/particleWithKineticEnergy range892 8929.0 8939.0 keV gamma
/score/quantity/flatSurfaceFlux fux893 
/score/filter/particleWithKineticEnergy range893 8939.0 8949.0 keV gamma
/score/quantity/flatSurfaceFlux fux894 
/score/filter/particleWithKineticEnergy range894 8949.0 8959.0 keV gamma
/score/quantity/flatSurfaceFlux fux895 
/score/filter/particleWithKineticEnergy range895 8959.0 8969.0 keV gamma
/score/quantity/flatSurfaceFlux fux896 
/score/filter/particleWithKineticEnergy range896 8969.0 8979.0 keV gamma
/score/quantity/flatSurfaceFlux fux897 
/score/filter/particleWithKineticEnergy range897 8979.0 8989.0 keV gamma
/score/quantity/flatSurfaceFlux fux898 
/score/filter/particleWithKineticEnergy range898 8989.0 8999.0 keV gamma
/score/quantity/flatSurfaceFlux fux899 
/score/filter/particleWithKineticEnergy range899 8999.0 9009.0 keV gamma
/score/quantity/flatSurfaceFlux fux900 
/score/filter/particleWithKineticEnergy range900 9009.0 9019.0 keV gamma
/score/quantity/flatSurfaceFlux fux901 
/score/filter/particleWithKineticEnergy range901 9019.0 9029.0 keV gamma
/score/quantity/flatSurfaceFlux fux902 
/score/filter/particleWithKineticEnergy range902 9029.0 9039.0 keV gamma
/score/quantity/flatSurfaceFlux fux903 
/score/filter/particleWithKineticEnergy range903 9039.0 9049.0 keV gamma
/score/quantity/flatSurfaceFlux fux904 
/score/filter/particleWithKineticEnergy range904 9049.0 9059.0 keV gamma
/score/quantity/flatSurfaceFlux fux905 
/score/filter/particleWithKineticEnergy range905 9059.0 9069.0 keV gamma
/score/quantity/flatSurfaceFlux fux906 
/score/filter/particleWithKineticEnergy range906 9069.0 9079.0 keV gamma
/score/quantity/flatSurfaceFlux fux907 
/score/filter/particleWithKineticEnergy range907 9079.0 9089.0 keV gamma
/score/quantity/flatSurfaceFlux fux908 
/score/filter/particleWithKineticEnergy range908 9089.0 9099.0 keV gamma
/score/quantity/flatSurfaceFlux fux909 
/score/filter/particleWithKineticEnergy range909 9099.0 9109.0 keV gamma
/score/quantity/flatSurfaceFlux fux910 
/score/filter/particleWithKineticEnergy range910 9109.0 9119.0 keV gamma
/score/quantity/flatSurfaceFlux fux911 
/score/filter/particleWithKineticEnergy range911 9119.0 9129.0 keV gamma
/score/quantity/flatSurfaceFlux fux912 
/score/filter/particleWithKineticEnergy range912 9129.0 9139.0 keV gamma
/score/quantity/flatSurfaceFlux fux913 
/score/filter/particleWithKineticEnergy range913 9139.0 9149.0 keV gamma
/score/quantity/flatSurfaceFlux fux914 
/score/filter/particleWithKineticEnergy range914 9149.0 9159.0 keV gamma
/score/quantity/flatSurfaceFlux fux915 
/score/filter/particleWithKineticEnergy range915 9159.0 9169.0 keV gamma
/score/quantity/flatSurfaceFlux fux916 
/score/filter/particleWithKineticEnergy range916 9169.0 9179.0 keV gamma
/score/quantity/flatSurfaceFlux fux917 
/score/filter/particleWithKineticEnergy range917 9179.0 9189.0 keV gamma
/score/quantity/flatSurfaceFlux fux918 
/score/filter/particleWithKineticEnergy range918 9189.0 9199.0 keV gamma
/score/quantity/flatSurfaceFlux fux919 
/score/filter/particleWithKineticEnergy range919 9199.0 9209.0 keV gamma
/score/quantity/flatSurfaceFlux fux920 
/score/filter/particleWithKineticEnergy range920 9209.0 9219.0 keV gamma
/score/quantity/flatSurfaceFlux fux921 
/score/filter/particleWithKineticEnergy range921 9219.0 9229.0 keV gamma
/score/quantity/flatSurfaceFlux fux922 
/score/filter/particleWithKineticEnergy range922 9229.0 9239.0 keV gamma
/score/quantity/flatSurfaceFlux fux923 
/score/filter/particleWithKineticEnergy range923 9239.0 9249.0 keV gamma
/score/quantity/flatSurfaceFlux fux924 
/score/filter/particleWithKineticEnergy range924 9249.0 9259.0 keV gamma
/score/quantity/flatSurfaceFlux fux925 
/score/filter/particleWithKineticEnergy range925 9259.0 9269.0 keV gamma
/score/quantity/flatSurfaceFlux fux926 
/score/filter/particleWithKineticEnergy range926 9269.0 9279.0 keV gamma
/score/quantity/flatSurfaceFlux fux927 
/score/filter/particleWithKineticEnergy range927 9279.0 9289.0 keV gamma
/score/quantity/flatSurfaceFlux fux928 
/score/filter/particleWithKineticEnergy range928 9289.0 9299.0 keV gamma
/score/quantity/flatSurfaceFlux fux929 
/score/filter/particleWithKineticEnergy range929 9299.0 9309.0 keV gamma
/score/quantity/flatSurfaceFlux fux930 
/score/filter/particleWithKineticEnergy range930 9309.0 9319.0 keV gamma
/score/quantity/flatSurfaceFlux fux931 
/score/filter/particleWithKineticEnergy range931 9319.0 9329.0 keV gamma
/score/quantity/flatSurfaceFlux fux932 
/score/filter/particleWithKineticEnergy range932 9329.0 9339.0 keV gamma
/score/quantity/flatSurfaceFlux fux933 
/score/filter/particleWithKineticEnergy range933 9339.0 9349.0 keV gamma
/score/quantity/flatSurfaceFlux fux934 
/score/filter/particleWithKineticEnergy range934 9349.0 9359.0 keV gamma
/score/quantity/flatSurfaceFlux fux935 
/score/filter/particleWithKineticEnergy range935 9359.0 9369.0 keV gamma
/score/quantity/flatSurfaceFlux fux936 
/score/filter/particleWithKineticEnergy range936 9369.0 9379.0 keV gamma
/score/quantity/flatSurfaceFlux fux937 
/score/filter/particleWithKineticEnergy range937 9379.0 9389.0 keV gamma
/score/quantity/flatSurfaceFlux fux938 
/score/filter/particleWithKineticEnergy range938 9389.0 9399.0 keV gamma
/score/quantity/flatSurfaceFlux fux939 
/score/filter/particleWithKineticEnergy range939 9399.0 9409.0 keV gamma
/score/quantity/flatSurfaceFlux fux940 
/score/filter/particleWithKineticEnergy range940 9409.0 9419.0 keV gamma
/score/quantity/flatSurfaceFlux fux941 
/score/filter/particleWithKineticEnergy range941 9419.0 9429.0 keV gamma
/score/quantity/flatSurfaceFlux fux942 
/score/filter/particleWithKineticEnergy range942 9429.0 9439.0 keV gamma
/score/quantity/flatSurfaceFlux fux943 
/score/filter/particleWithKineticEnergy range943 9439.0 9449.0 keV gamma
/score/quantity/flatSurfaceFlux fux944 
/score/filter/particleWithKineticEnergy range944 9449.0 9459.0 keV gamma
/score/quantity/flatSurfaceFlux fux945 
/score/filter/particleWithKineticEnergy range945 9459.0 9469.0 keV gamma
/score/quantity/flatSurfaceFlux fux946 
/score/filter/particleWithKineticEnergy range946 9469.0 9479.0 keV gamma
/score/quantity/flatSurfaceFlux fux947 
/score/filter/particleWithKineticEnergy range947 9479.0 9489.0 keV gamma
/score/quantity/flatSurfaceFlux fux948 
/score/filter/particleWithKineticEnergy range948 9489.0 9499.0 keV gamma
/score/quantity/flatSurfaceFlux fux949 
/score/filter/particleWithKineticEnergy range949 9499.0 9510.0 keV gamma
/score/quantity/flatSurfaceFlux fux950 
/score/filter/particleWithKineticEnergy range950 9510.0 9520.0 keV gamma
/score/quantity/flatSurfaceFlux fux951 
/score/filter/particleWithKineticEnergy range951 9520.0 9530.0 keV gamma
/score/quantity/flatSurfaceFlux fux952 
/score/filter/particleWithKineticEnergy range952 9530.0 9540.0 keV gamma
/score/quantity/flatSurfaceFlux fux953 
/score/filter/particleWithKineticEnergy range953 9540.0 9550.0 keV gamma
/score/quantity/flatSurfaceFlux fux954 
/score/filter/particleWithKineticEnergy range954 9550.0 9560.0 keV gamma
/score/quantity/flatSurfaceFlux fux955 
/score/filter/particleWithKineticEnergy range955 9560.0 9570.0 keV gamma
/score/quantity/flatSurfaceFlux fux956 
/score/filter/particleWithKineticEnergy range956 9570.0 9580.0 keV gamma
/score/quantity/flatSurfaceFlux fux957 
/score/filter/particleWithKineticEnergy range957 9580.0 9590.0 keV gamma
/score/quantity/flatSurfaceFlux fux958 
/score/filter/particleWithKineticEnergy range958 9590.0 9600.0 keV gamma
/score/quantity/flatSurfaceFlux fux959 
/score/filter/particleWithKineticEnergy range959 9600.0 9610.0 keV gamma
/score/quantity/flatSurfaceFlux fux960 
/score/filter/particleWithKineticEnergy range960 9610.0 9620.0 keV gamma
/score/quantity/flatSurfaceFlux fux961 
/score/filter/particleWithKineticEnergy range961 9620.0 9630.0 keV gamma
/score/quantity/flatSurfaceFlux fux962 
/score/filter/particleWithKineticEnergy range962 9630.0 9640.0 keV gamma
/score/quantity/flatSurfaceFlux fux963 
/score/filter/particleWithKineticEnergy range963 9640.0 9650.0 keV gamma
/score/quantity/flatSurfaceFlux fux964 
/score/filter/particleWithKineticEnergy range964 9650.0 9660.0 keV gamma
/score/quantity/flatSurfaceFlux fux965 
/score/filter/particleWithKineticEnergy range965 9660.0 9670.0 keV gamma
/score/quantity/flatSurfaceFlux fux966 
/score/filter/particleWithKineticEnergy range966 9670.0 9680.0 keV gamma
/score/quantity/flatSurfaceFlux fux967 
/score/filter/particleWithKineticEnergy range967 9680.0 9690.0 keV gamma
/score/quantity/flatSurfaceFlux fux968 
/score/filter/particleWithKineticEnergy range968 9690.0 9700.0 keV gamma
/score/quantity/flatSurfaceFlux fux969 
/score/filter/particleWithKineticEnergy range969 9700.0 9710.0 keV gamma
/score/quantity/flatSurfaceFlux fux970 
/score/filter/particleWithKineticEnergy range970 9710.0 9720.0 keV gamma
/score/quantity/flatSurfaceFlux fux971 
/score/filter/particleWithKineticEnergy range971 9720.0 9730.0 keV gamma
/score/quantity/flatSurfaceFlux fux972 
/score/filter/particleWithKineticEnergy range972 9730.0 9740.0 keV gamma
/score/quantity/flatSurfaceFlux fux973 
/score/filter/particleWithKineticEnergy range973 9740.0 9750.0 keV gamma
/score/quantity/flatSurfaceFlux fux974 
/score/filter/particleWithKineticEnergy range974 9750.0 9760.0 keV gamma
/score/quantity/flatSurfaceFlux fux975 
/score/filter/particleWithKineticEnergy range975 9760.0 9770.0 keV gamma
/score/quantity/flatSurfaceFlux fux976 
/score/filter/particleWithKineticEnergy range976 9770.0 9780.0 keV gamma
/score/quantity/flatSurfaceFlux fux977 
/score/filter/particleWithKineticEnergy range977 9780.0 9790.0 keV gamma
/score/quantity/flatSurfaceFlux fux978 
/score/filter/particleWithKineticEnergy range978 9790.0 9800.0 keV gamma
/score/quantity/flatSurfaceFlux fux979 
/score/filter/particleWithKineticEnergy range979 9800.0 9810.0 keV gamma
/score/quantity/flatSurfaceFlux fux980 
/score/filter/particleWithKineticEnergy range980 9810.0 9820.0 keV gamma
/score/quantity/flatSurfaceFlux fux981 
/score/filter/particleWithKineticEnergy range981 9820.0 9830.0 keV gamma
/score/quantity/flatSurfaceFlux fux982 
/score/filter/particleWithKineticEnergy range982 9830.0 9840.0 keV gamma
/score/quantity/flatSurfaceFlux fux983 
/score/filter/particleWithKineticEnergy range983 9840.0 9850.0 keV gamma
/score/quantity/flatSurfaceFlux fux984 
/score/filter/particleWithKineticEnergy range984 9850.0 9860.0 keV gamma
/score/quantity/flatSurfaceFlux fux985 
/score/filter/particleWithKineticEnergy range985 9860.0 9870.0 keV gamma
/score/quantity/flatSurfaceFlux fux986 
/score/filter/particleWithKineticEnergy range986 9870.0 9880.0 keV gamma
/score/quantity/flatSurfaceFlux fux987 
/score/filter/particleWithKineticEnergy range987 9880.0 9890.0 keV gamma
/score/quantity/flatSurfaceFlux fux988 
/score/filter/particleWithKineticEnergy range988 9890.0 9900.0 keV gamma
/score/quantity/flatSurfaceFlux fux989 
/score/filter/particleWithKineticEnergy range989 9900.0 9910.0 keV gamma
/score/quantity/flatSurfaceFlux fux990 
/score/filter/particleWithKineticEnergy range990 9910.0 9920.0 keV gamma
/score/quantity/flatSurfaceFlux fux991 
/score/filter/particleWithKineticEnergy range991 9920.0 9930.0 keV gamma
/score/quantity/flatSurfaceFlux fux992 
/score/filter/particleWithKineticEnergy range992 9930.0 9940.0 keV gamma
/score/quantity/flatSurfaceFlux fux993 
/score/filter/particleWithKineticEnergy range993 9940.0 9950.0 keV gamma
/score/quantity/flatSurfaceFlux fux994 
/score/filter/particleWithKineticEnergy range994 9950.0 9960.0 keV gamma
/score/quantity/flatSurfaceFlux fux995 
/score/filter/particleWithKineticEnergy range995 9960.0 9970.0 keV gamma
/score/quantity/flatSurfaceFlux fux996 
/score/filter/particleWithKineticEnergy range996 9970.0 9980.0 keV gamma
/score/quantity/flatSurfaceFlux fux997 
/score/filter/particleWithKineticEnergy range997 9980.0 9990.0 keV gamma
/score/quantity/flatSurfaceFlux fux998 
/score/filter/particleWithKineticEnergy range998 9990.0 10000.0 keV gamma
/score/close
/score/list